const QUESTIONS = {
  "80'er Hits": [
    { q: "Hvilket band sang 'Take On Me' i 1985?", a: "a-ha", options: ["a-ha", "Duran Duran", "Depeche Mode", "Pet Shop Boys"] },
    { q: "Hvem sang 'Billie Jean'?", a: "Michael Jackson", options: ["Prince", "Michael Jackson", "Stevie Wonder", "Lionel Richie"] },
    { q: "Hvilket band stod bag 'Sweet Child O' Mine'?", a: "Guns N' Roses", options: ["Guns N' Roses", "Bon Jovi", "Mötley Crüe", "Def Leppard"] },
    { q: "Hvem sang 'Like a Virgin' i 1984?", a: "Madonna", options: ["Cyndi Lauper", "Madonna", "Whitney Houston", "Janet Jackson"] },
    { q: "Hvilket band sang 'Every Breath You Take'?", a: "The Police", options: ["U2", "The Police", "Dire Straits", "The Cure"] },
    { q: "Hvem sang 'Purple Rain'?", a: "Prince", options: ["Michael Jackson", "Prince", "David Bowie", "George Michael"] },
    { q: "Hvilket band sang 'Don't Stop Believin''?", a: "Journey", options: ["Journey", "Foreigner", "REO Speedwagon", "Styx"] },
    { q: "Hvem sang 'Girls Just Want to Have Fun'?", a: "Cyndi Lauper", options: ["Madonna", "Cyndi Lauper", "Blondie", "Pat Benatar"] },
    { q: "Hvilket band stod bag 'The Final Countdown'?", a: "Europe", options: ["Europe", "Whitesnake", "Scorpions", "Accept"] },
    { q: "Hvem sang 'I Wanna Dance with Somebody'?", a: "Whitney Houston", options: ["Whitney Houston", "Janet Jackson", "Diana Ross", "Tina Turner"] },
    { q: "Hvilket band sang 'Livin' on a Prayer'?", a: "Bon Jovi", options: ["Def Leppard", "Bon Jovi", "Whitesnake", "Poison"] },
    { q: "Hvem sang 'West End Girls'?", a: "Pet Shop Boys", options: ["Erasure", "Pet Shop Boys", "Soft Cell", "Depeche Mode"] },
    { q: "Hvilket band sang 'Enjoy the Silence'?", a: "Depeche Mode", options: ["New Order", "Depeche Mode", "The Cure", "Tears for Fears"] },
    { q: "Hvem sang 'Karma Chameleon'?", a: "Culture Club", options: ["Duran Duran", "Spandau Ballet", "Culture Club", "Wham!"] },
    { q: "Hvilket band sang 'Money for Nothing'?", a: "Dire Straits", options: ["Dire Straits", "Pink Floyd", "ZZ Top", "The Eagles"] },
    { q: "Hvem sang 'Wake Me Up Before You Go-Go'?", a: "Wham!", options: ["Duran Duran", "Culture Club", "Wham!", "Frankie Goes to Hollywood"] },
    { q: "Hvilket band sang 'With or Without You'?", a: "U2", options: ["U2", "Simple Minds", "INXS", "The Cure"] },
    { q: "Hvem sang 'Tainted Love'?", a: "Soft Cell", options: ["Depeche Mode", "Soft Cell", "Pet Shop Boys", "Erasure"] },
    { q: "Hvilket band sang 'Shout'?", a: "Tears for Fears", options: ["Simple Minds", "Tears for Fears", "Duran Duran", "Spandau Ballet"] },
    { q: "Hvem sang 'Relax'?", a: "Frankie Goes to Hollywood", options: ["Wham!", "Frankie Goes to Hollywood", "Pet Shop Boys", "Erasure"] },
    { q: "Hvilket band sang 'Blue Monday'?", a: "New Order", options: ["Depeche Mode", "New Order", "Joy Division", "The Smiths"] },
    { q: "Hvem sang 'Addicted to Love'?", a: "Robert Palmer", options: ["Bryan Adams", "Robert Palmer", "Phil Collins", "Rick Springfield"] },
    { q: "Hvilket band sang 'Jump'?", a: "Van Halen", options: ["Van Halen", "Def Leppard", "AC/DC", "Scorpions"] },
    { q: "Hvem sang 'Private Eyes'?", a: "Hall & Oates", options: ["The Police", "Hall & Oates", "Duran Duran", "Tears for Fears"] },
    { q: "Hvilket band sang 'Under Pressure'?", a: "Queen & David Bowie", options: ["Queen & David Bowie", "Dire Straits", "Genesis", "The Police"] },
    { q: "Hvem sang 'Never Gonna Give You Up'?", a: "Rick Astley", options: ["George Michael", "Rick Astley", "Billy Ocean", "Bobby Brown"] },
    { q: "Hvilket band sang 'Hunger Strike'?", a: "Temple of the Dog", options: ["Pearl Jam", "Temple of the Dog", "Soundgarden", "Alice in Chains"] },
    { q: "Hvem sang 'Faith'?", a: "George Michael", options: ["George Michael", "Rick Astley", "Phil Collins", "Sting"] },
    { q: "Hvilket band sang 'Pour Some Sugar on Me'?", a: "Def Leppard", options: ["Def Leppard", "Poison", "Mötley Crüe", "Bon Jovi"] },
    { q: "Hvem sang 'Africa'?", a: "Toto", options: ["Toto", "Genesis", "Phil Collins", "Foreigner"] },
    { q: "Hvilket band sang 'Need You Tonight'?", a: "INXS", options: ["INXS", "Duran Duran", "Simple Minds", "U2"] }
  ],
  "90'er Hits": [
    { q: "Hvilket band sang 'Smells Like Teen Spirit'?", a: "Nirvana", options: ["Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains"] },
    { q: "Hvem sang 'Wannabe' i 1996?", a: "Spice Girls", options: ["Spice Girls", "All Saints", "Destiny's Child", "TLC"] },
    { q: "Hvilket band sang 'Creep'?", a: "Radiohead", options: ["Radiohead", "Oasis", "Blur", "Pulp"] },
    { q: "Hvem sang 'I Will Always Love You' (filmversion)?", a: "Whitney Houston", options: ["Mariah Carey", "Whitney Houston", "Celine Dion", "Dolly Parton"] },
    { q: "Hvilket band sang 'Wonderwall'?", a: "Oasis", options: ["Blur", "Oasis", "Radiohead", "The Verve"] },
    { q: "Hvem sang 'No Diggity'?", a: "Blackstreet", options: ["Blackstreet", "Boyz II Men", "TLC", "SWV"] },
    { q: "Hvilket band sang 'Losing My Religion'?", a: "R.E.M.", options: ["R.E.M.", "U2", "Pearl Jam", "The Cranberries"] },
    { q: "Hvem sang 'Baby One More Time'?", a: "Britney Spears", options: ["Christina Aguilera", "Britney Spears", "Mandy Moore", "Jessica Simpson"] },
    { q: "Hvilket band sang 'Bitter Sweet Symphony'?", a: "The Verve", options: ["Oasis", "The Verve", "Blur", "Radiohead"] },
    { q: "Hvem sang 'Waterfalls'?", a: "TLC", options: ["Destiny's Child", "TLC", "En Vogue", "SWV"] },
    { q: "Hvilket band sang 'Under the Bridge'?", a: "Red Hot Chili Peppers", options: ["Pearl Jam", "Red Hot Chili Peppers", "Nirvana", "Soundgarden"] },
    { q: "Hvem sang 'My Heart Will Go On'?", a: "Celine Dion", options: ["Whitney Houston", "Celine Dion", "Mariah Carey", "Barbra Streisand"] },
    { q: "Hvilket band sang 'Song 2'?", a: "Blur", options: ["Oasis", "Blur", "Pulp", "Suede"] },
    { q: "Hvem sang 'Gangsta's Paradise'?", a: "Coolio", options: ["Coolio", "2Pac", "Notorious B.I.G.", "Snoop Dogg"] },
    { q: "Hvilket band sang 'Zombie'?", a: "The Cranberries", options: ["The Cranberries", "Garbage", "No Doubt", "Hole"] },
    { q: "Hvem sang 'MMMBop'?", a: "Hanson", options: ["Backstreet Boys", "Hanson", "*NSYNC", "98 Degrees"] },
    { q: "Hvilket band sang 'Everybody (Backstreet's Back)'?", a: "Backstreet Boys", options: ["Backstreet Boys", "*NSYNC", "Westlife", "98 Degrees"] },
    { q: "Hvem sang 'Livin' La Vida Loca'?", a: "Ricky Martin", options: ["Enrique Iglesias", "Ricky Martin", "Marc Anthony", "Julio Iglesias"] },
    { q: "Hvilket band sang 'Enter Sandman'?", a: "Metallica", options: ["Metallica", "Megadeth", "Slayer", "Pantera"] },
    { q: "Hvem sang 'I Believe I Can Fly'?", a: "R. Kelly", options: ["R. Kelly", "Seal", "Boyz II Men", "Brian McKnight"] },
    { q: "Hvilket band sang 'Common People'?", a: "Pulp", options: ["Oasis", "Blur", "Pulp", "The Verve"] },
    { q: "Hvem sang 'Torn'?", a: "Natalie Imbruglia", options: ["Natalie Imbruglia", "Alanis Morissette", "Sheryl Crow", "Jewel"] },
    { q: "Hvilket band sang 'No Rain'?", a: "Blind Melon", options: ["Blind Melon", "Stone Temple Pilots", "Bush", "Live"] },
    { q: "Hvem sang 'Ironic'?", a: "Alanis Morissette", options: ["Alanis Morissette", "Sheryl Crow", "Fiona Apple", "Tori Amos"] },
    { q: "Hvilket band sang 'Black Hole Sun'?", a: "Soundgarden", options: ["Pearl Jam", "Nirvana", "Soundgarden", "Alice in Chains"] },
    { q: "Hvem sang 'Kiss from a Rose'?", a: "Seal", options: ["Seal", "Sade", "Des'ree", "Terence Trent D'Arby"] },
    { q: "Hvilket band sang 'Killing in the Name'?", a: "Rage Against the Machine", options: ["Rage Against the Machine", "System of a Down", "Korn", "Tool"] },
    { q: "Hvem sang 'Return of the Mack'?", a: "Mark Morrison", options: ["Craig David", "Mark Morrison", "Shaggy", "Sean Paul"] },
    { q: "Hvilket band sang 'Basket Case'?", a: "Green Day", options: ["Green Day", "Blink-182", "The Offspring", "Bad Religion"] },
    { q: "Hvem sang 'You Oughta Know'?", a: "Alanis Morissette", options: ["Alanis Morissette", "Sheryl Crow", "Courtney Love", "PJ Harvey"] },
    { q: "Hvilket band sang 'Tubthumping'?", a: "Chumbawamba", options: ["Chumbawamba", "The Prodigy", "Fatboy Slim", "Underworld"] }
  ],
  "Klassisk Rock": [
    { q: "Hvilket band sang 'Stairway to Heaven'?", a: "Led Zeppelin", options: ["Led Zeppelin", "Deep Purple", "Black Sabbath", "Pink Floyd"] },
    { q: "Hvem sang 'Bohemian Rhapsody'?", a: "Queen", options: ["Queen", "The Rolling Stones", "The Beatles", "The Who"] },
    { q: "Hvilket band sang 'Hotel California'?", a: "Eagles", options: ["Eagles", "Fleetwood Mac", "The Doors", "Creedence Clearwater Revival"] },
    { q: "Hvem sang 'Satisfaction'?", a: "The Rolling Stones", options: ["The Rolling Stones", "The Beatles", "The Who", "The Kinks"] },
    { q: "Hvilket band sang 'Comfortably Numb'?", a: "Pink Floyd", options: ["Led Zeppelin", "Pink Floyd", "Yes", "Genesis"] },
    { q: "Hvem sang 'Born to Run'?", a: "Bruce Springsteen", options: ["Bruce Springsteen", "Bob Seger", "Tom Petty", "John Mellencamp"] },
    { q: "Hvilket band sang 'Smoke on the Water'?", a: "Deep Purple", options: ["Led Zeppelin", "Deep Purple", "Black Sabbath", "Uriah Heep"] },
    { q: "Hvem sang 'Imagine'?", a: "John Lennon", options: ["Paul McCartney", "John Lennon", "George Harrison", "Ringo Starr"] },
    { q: "Hvilket band sang 'Highway to Hell'?", a: "AC/DC", options: ["AC/DC", "Motörhead", "Judas Priest", "Iron Maiden"] },
    { q: "Hvem sang 'Space Oddity'?", a: "David Bowie", options: ["Elton John", "David Bowie", "Peter Gabriel", "Marc Bolan"] },
    { q: "Hvilket band sang 'Wish You Were Here'?", a: "Pink Floyd", options: ["Pink Floyd", "Led Zeppelin", "Genesis", "Yes"] },
    { q: "Hvem sang 'Born in the U.S.A.'?", a: "Bruce Springsteen", options: ["Bruce Springsteen", "John Mellencamp", "Tom Petty", "Bob Seger"] },
    { q: "Hvilket band sang 'Paranoid'?", a: "Black Sabbath", options: ["Black Sabbath", "Led Zeppelin", "Deep Purple", "Judas Priest"] },
    { q: "Hvem sang 'Let It Be'?", a: "The Beatles", options: ["The Beatles", "The Rolling Stones", "The Who", "The Kinks"] },
    { q: "Hvilket band sang 'Free Bird'?", a: "Lynyrd Skynyrd", options: ["Lynyrd Skynyrd", "The Allman Brothers Band", "ZZ Top", "Eagles"] },
    { q: "Hvem sang 'Light My Fire'?", a: "The Doors", options: ["The Doors", "Jimi Hendrix", "The Rolling Stones", "Cream"] },
    { q: "Hvilket band sang 'We Will Rock You'?", a: "Queen", options: ["Queen", "Kiss", "AC/DC", "Aerosmith"] },
    { q: "Hvilket band — anført af Eric Clapton — sang 'Layla'?", a: "Derek and the Dominos", options: ["Derek and the Dominos", "Cream", "The Yardbirds", "Blind Faith"] },
    { q: "Hvilket band sang 'Roxanne'?", a: "The Police", options: ["The Clash", "The Police", "The Jam", "Blondie"] },
    { q: "Hvem sang 'Whole Lotta Love'?", a: "Led Zeppelin", options: ["Led Zeppelin", "Deep Purple", "Black Sabbath", "The Who"] },
    { q: "Hvilket band sang 'Won't Get Fooled Again'?", a: "The Who", options: ["The Who", "The Rolling Stones", "The Clash", "The Kinks"] },
    { q: "Hvem sang 'Ziggy Stardust'?", a: "David Bowie", options: ["David Bowie", "T. Rex", "Roxy Music", "Lou Reed"] },
    { q: "Hvilket band sang 'Dream On'?", a: "Aerosmith", options: ["Aerosmith", "Kiss", "Alice Cooper", "Van Halen"] },
    { q: "Hvem sang 'Thunder Road'?", a: "Bruce Springsteen", options: ["Bruce Springsteen", "Bob Seger", "Tom Petty", "Jackson Browne"] },
    { q: "Hvilket band sang 'Sultans of Swing'?", a: "Dire Straits", options: ["Dire Straits", "Fleetwood Mac", "Eagles", "The Police"] },
    { q: "Hvem sang 'All Along the Watchtower' (mest kendte version)?", a: "Jimi Hendrix", options: ["Bob Dylan", "Jimi Hendrix", "Eric Clapton", "Neil Young"] },
    { q: "Hvilket band sang 'Paint It Black'?", a: "The Rolling Stones", options: ["The Rolling Stones", "The Beatles", "The Doors", "The Kinks"] },
    { q: "Hvem sang 'Knockin' on Heaven's Door' (original)?", a: "Bob Dylan", options: ["Bob Dylan", "Eric Clapton", "Guns N' Roses", "Neil Young"] },
    { q: "Hvilket band sang 'Sunshine of Your Love'?", a: "Cream", options: ["Cream", "Led Zeppelin", "Jimi Hendrix Experience", "Deep Purple"] },
    { q: "Hvem sang 'Rocket Man'?", a: "Elton John", options: ["David Bowie", "Elton John", "Billy Joel", "Rod Stewart"] },
    { q: "Hvilket band sang 'Go Your Own Way'?", a: "Fleetwood Mac", options: ["Fleetwood Mac", "Eagles", "The Doobie Brothers", "Steely Dan"] }
  ],
  "Dansk Musik": [
    { q: "Hvem sang 'Midt Om Natten'?", a: "Kim Larsen", options: ["Kim Larsen", "Gasolin'", "TV-2", "Lars H.U.G."] },
    { q: "Hvilket dansk band sang 'Kvinde Min'?", a: "Gasolin'", options: ["Gasolin'", "Sort Sol", "TV-2", "Gnags"] },
    { q: "Hvem sang 'Sommer i Europa'?", a: "Thomas Helmig", options: ["Thomas Helmig", "Kim Larsen", "Rasmus Seebach", "Nik & Jay"] },
    { q: "Hvilket band sang 'Elskere i Natten'?", a: "Tøsedrengene", options: ["Tøsedrengene", "TV-2", "Gnags", "Rocazino"] },
    { q: "Hvem sang 'Gi' Mig Danmark Tilbage'?", a: "Kim Larsen", options: ["Kim Larsen", "Shu-bi-dua", "Gasolin'", "Sebastian"] },
    { q: "Hvilket band sang 'Nærmest Lykkelig'?", a: "TV-2", options: ["TV-2", "Tøsedrengene", "Gnags", "Kashmir"] },
    { q: "Hvem sang 'Det' Noget Med Ansen'?", a: "Shu-bi-dua", options: ["Shu-bi-dua", "Kim Larsen", "Gasolin'", "De Nattergale"] },
    { q: "Hvilket dansk band sang 'Rocket Boy'?", a: "Kashmir", options: ["Mew", "Kashmir", "Saybia", "Carpark North"] },
    { q: "Hvem sang 'Engel'?", a: "Nik & Jay", options: ["Nik & Jay", "Rasmus Seebach", "Joey Moe", "Burhan G"] },
    { q: "Hvilket band sang 'This Is My Life'?", a: "Gasolin'", options: ["Gasolin'", "Sort Sol", "D-A-D", "Pretty Maids"] },
    { q: "Hvem sang 'Den Jeg Elsker'?", a: "Rasmus Seebach", options: ["Thomas Helmig", "Rasmus Seebach", "Nik & Jay", "Kim Larsen"] },
    { q: "Hvilket band sang 'Sleeping My Day Away'?", a: "D-A-D", options: ["D-A-D", "Pretty Maids", "Sort Sol", "Volbeat"] },
    { q: "Hvem sang 'Rabalderstræde'?", a: "Gasolin'", options: ["Gasolin'", "Shu-bi-dua", "Kim Larsen", "Steppeulvene"] },
    { q: "Hvilket band sang 'Langebansen'?", a: "Gnags", options: ["Gnags", "TV-2", "Shu-bi-dua", "Tøsedrengene"] },
    { q: "Hvem sang 'Papirsklip'?", a: "Kim Larsen", options: ["Kim Larsen", "Sebastian", "Lars H.U.G.", "C.V. Jørgensen"] },
    { q: "Hvilket band vandt Eurovision for Danmark i 2000 med 'Fly on the Wings of Love'?", a: "Olsen Brothers", options: ["Olsen Brothers", "Aqua", "Rollo & King", "Tommy Seebach"] },
    { q: "Hvem sang 'Barbie Girl'?", a: "Aqua", options: ["Aqua", "Toy-Box", "Hit'n'Hide", "Tiggy"] },
    { q: "Hvilket dansk band sang 'Still Alive'?", a: "Volbeat", options: ["Volbeat", "D-A-D", "Pretty Maids", "Mercyful Fate"] },
    { q: "Hvem sang 'Nattog Til København'?", a: "C.V. Jørgensen", options: ["Kim Larsen", "C.V. Jørgensen", "Sebastian", "Lars H.U.G."] },
    { q: "Hvilket band sang 'Supermarket'?", a: "Shu-bi-dua", options: ["Shu-bi-dua", "Gnags", "Tøsedrengene", "TV-2"] },
    { q: "Hvem sang 'Floden'?", a: "Lars H.U.G.", options: ["Lars H.U.G.", "Kim Larsen", "Sebastian", "Thomas Helmig"] },
    { q: "Hvilket band sang 'Am I Wrong'?", a: "Nico & Vinz", options: ["Lukas Graham", "Nico & Vinz", "MØ", "Outlandish"] },
    { q: "Hvem sang '7 Years'?", a: "Lukas Graham", options: ["Lukas Graham", "Nico & Vinz", "MØ", "Christopher"] },
    { q: "Hvilket band sang 'Lean On' med Major Lazer?", a: "MØ", options: ["MØ", "Medina", "Aura Dione", "Agnes Obel"] },
    { q: "Hvem sang 'Dansen' med TV-2?", a: "Steffen Brandt", options: ["Steffen Brandt", "Kim Larsen", "Thomas Helmig", "Michael Falch"] },
    { q: "Hvilket band sang 'Let My Children Hear Music'?", a: "Sort Sol", options: ["Sort Sol", "Kashmir", "Mew", "Under Byen"] },
    { q: "Hvem sang 'Sig Du Ka' Li' Mansen'?", a: "Bamses Venner", options: ["Bamses Venner", "Shu-bi-dua", "Gnags", "Kim Larsen"] },
    { q: "Hvilket band sang '156'?", a: ["Mew"], options: ["Mew", "Kashmir", "Carpark North", "Saybia"] },
    { q: "Hvem sang 'Apache'?", a: "Jørgen Ingmann", options: ["Jørgen Ingmann", "The Shadows", "The Spotnicks", "Bent Fabric"] },
    { q: "Hvilket band sang 'Only Shallow' (dansk version)?", a: "Efterklang", options: ["Efterklang", "Under Byen", "Mew", "Sort Sol"] },
    { q: "Hvem sang 'Hvor Ku' Du Tro'?", a: "Anne Linnet", options: ["Anne Linnet", "Sanne Salomonsen", "Lis Sørensen", "Hanne Boel"] }
  ],
  "Film Soundtracks": [
    { q: "Hvilken film er 'Stayin' Alive' af Bee Gees fra?", a: "Saturday Night Fever", options: ["Saturday Night Fever", "Grease", "Dirty Dancing", "Footloose"] },
    { q: "Hvem sang 'Eye of the Tiger' fra Rocky III?", a: "Survivor", options: ["Survivor", "Journey", "Foreigner", "REO Speedwagon"] },
    { q: "Hvilken film bruger 'Danger Zone' af Kenny Loggins?", a: "Top Gun", options: ["Top Gun", "Footloose", "Flashdance", "Beverly Hills Cop"] },
    { q: "Hvem sang 'Ghostbusters' temasangen?", a: "Ray Parker Jr.", options: ["Ray Parker Jr.", "Huey Lewis", "Rick Springfield", "Billy Ocean"] },
    { q: "Hvilken film er 'The Time of My Life' fra?", a: "Dirty Dancing", options: ["Dirty Dancing", "Flashdance", "Footloose", "Grease"] },
    { q: "Hvem sang 'Lose Yourself' fra 8 Mile?", a: "Eminem", options: ["Eminem", "50 Cent", "Jay-Z", "Kanye West"] },
    { q: "Hvilken film er 'Don't You (Forget About Me)' fra?", a: "The Breakfast Club", options: ["The Breakfast Club", "Pretty in Pink", "Sixteen Candles", "Ferris Bueller's Day Off"] },
    { q: "Hvem sang temaet til James Bond-filmen 'Goldfinger'?", a: "Shirley Bassey", options: ["Shirley Bassey", "Tom Jones", "Nancy Sinatra", "Dusty Springfield"] },
    { q: "Hvilken film er 'Hakuna Matata' fra?", a: "Løvernes Konge", options: ["Løvernes Konge", "Aladdin", "Jungle Book", "Tarzan"] },
    { q: "Hvem sang 'Skyfall' til James Bond-filmen?", a: "Adele", options: ["Adele", "Sam Smith", "Billie Eilish", "Alicia Keys"] },
    { q: "Hvilken film er 'Footloose' temasangen fra?", a: "Footloose", options: ["Footloose", "Flashdance", "Dirty Dancing", "Fame"] },
    { q: "Hvem sang 'Maniac' fra Flashdance?", a: "Michael Sembello", options: ["Michael Sembello", "Irene Cara", "Kenny Loggins", "Jennifer Beals"] },
    { q: "Hvilken film bruger 'Mrs. Robinson' af Simon & Garfunkel?", a: "The Graduate", options: ["The Graduate", "Butch Cassidy", "Easy Rider", "Midnight Cowboy"] },
    { q: "Hvem sang 'Let It Go' fra Frozen?", a: "Idina Menzel", options: ["Idina Menzel", "Kristen Bell", "Demi Lovato", "Elsa"] },
    { q: "Hvilken film er 'Shallow' fra?", a: "A Star Is Born", options: ["A Star Is Born", "La La Land", "The Greatest Showman", "Bohemian Rhapsody"] },
    { q: "Hvem komponerede musikken til Star Wars?", a: "John Williams", options: ["John Williams", "Hans Zimmer", "Howard Shore", "James Horner"] },
    { q: "Hvilken film er 'Raindrops Keep Fallin' on My Head' fra?", a: "Butch Cassidy and the Sundance Kid", options: ["Butch Cassidy and the Sundance Kid", "The Graduate", "Easy Rider", "Midnight Cowboy"] },
    { q: "Hvem sang 'Take My Breath Away' fra Top Gun?", a: "Berlin", options: ["Berlin", "Heart", "Bonnie Tyler", "Pat Benatar"] },
    { q: "Hvilken film er 'Everybody's Talkin'' fra?", a: "Midnight Cowboy", options: ["Midnight Cowboy", "Easy Rider", "The Graduate", "Butch Cassidy"] },
    { q: "Hvem komponerede musikken til Ringenes Herre?", a: "Howard Shore", options: ["Howard Shore", "John Williams", "Hans Zimmer", "James Horner"] },
    { q: "Hvilken film er 'Old Time Rock and Roll' forbundet med?", a: "Risky Business", options: ["Risky Business", "Footloose", "The Big Chill", "Back to the Future"] },
    { q: "Hvem sang 'Happy' fra Grusomme Mig 2?", a: "Pharrell Williams", options: ["Pharrell Williams", "Bruno Mars", "Justin Timberlake", "will.i.am"] },
    { q: "Hvilken film er 'Bohemian Rhapsody' af Queen brugt i (berømt bilscene)?", a: "Wayne's World", options: ["Wayne's World", "Bohemian Rhapsody", "Rocketman", "Dazed and Confused"] },
    { q: "Hvem sang 'I Don't Want to Miss a Thing' fra Armageddon?", a: "Aerosmith", options: ["Aerosmith", "Bon Jovi", "Bryan Adams", "Journey"] },
    { q: "Hvilken film er 'The Power of Love' af Huey Lewis fra?", a: "Tilbage til Fremtiden", options: ["Tilbage til Fremtiden", "Top Gun", "Beverly Hills Cop", "Ghostbusters"] },
    { q: "Hvem sang temaet fra Titanic?", a: "Celine Dion", options: ["Celine Dion", "Whitney Houston", "Mariah Carey", "Barbra Streisand"] },
    { q: "Hvilken film er 'A Whole New World' fra?", a: "Aladdin", options: ["Aladdin", "Løvernes Konge", "Den Lille Havfrue", "Skønheden og Udyret"] },
    { q: "Hvem komponerede musikken til Pirates of the Caribbean?", a: "Hans Zimmer", options: ["Hans Zimmer", "John Williams", "Howard Shore", "Danny Elfman"] },
    { q: "Hvilken film er 'Stuck in the Middle with You' berømt brugt i?", a: "Reservoir Dogs", options: ["Reservoir Dogs", "Pulp Fiction", "Kill Bill", "Snatch"] },
    { q: "Hvem sang 'Writing's on the Wall' til Spectre?", a: "Sam Smith", options: ["Sam Smith", "Adele", "Ed Sheeran", "Chris Cornell"] },
    { q: "Hvilken film bruger 'Immigrant Song' af Led Zeppelin i åbningsscenen?", a: "Thor: Ragnarok", options: ["Thor: Ragnarok", "Shrek", "School of Rock", "Zeppelin!"] }
  ],
  "Gæt Sangteksten": [
    { q: "'Is this the real life? Is this just fantasy?'", a: "Bohemian Rhapsody – Queen", options: ["Bohemian Rhapsody – Queen", "Comfortably Numb – Pink Floyd", "Space Oddity – David Bowie", "Imagine – John Lennon"] },
    { q: "'Ground control to Major Tom...'", a: "Space Oddity – David Bowie", options: ["Rocket Man – Elton John", "Space Oddity – David Bowie", "Starman – David Bowie", "Life on Mars – David Bowie"] },
    { q: "'Hello, is it me you're looking for?'", a: "Hello – Lionel Richie", options: ["Hello – Adele", "Hello – Lionel Richie", "Is This Love – Bob Marley", "Careless Whisper – George Michael"] },
    { q: "'We're no strangers to love, you know the rules and so do I'", a: "Never Gonna Give You Up – Rick Astley", options: ["Never Gonna Give You Up – Rick Astley", "Take On Me – a-ha", "Together Forever – Rick Astley", "Careless Whisper – George Michael"] },
    { q: "'Just a small town girl, livin' in a lonely world'", a: "Don't Stop Believin' – Journey", options: ["Don't Stop Believin' – Journey", "Livin' on a Prayer – Bon Jovi", "Faithfully – Journey", "Open Arms – Journey"] },
    { q: "'Midt om natten, når du ka' høre havets stemmer'", a: "Midt Om Natten – Kim Larsen", options: ["Midt Om Natten – Kim Larsen", "Papirsklip – Kim Larsen", "Køb Banansen – Kim Larsen", "Om Lidt – Kim Larsen"] },
    { q: "'I see a red door and I want it painted black'", a: "Paint It Black – The Rolling Stones", options: ["Paint It Black – The Rolling Stones", "Sympathy for the Devil – The Rolling Stones", "Black Dog – Led Zeppelin", "Back in Black – AC/DC"] },
    { q: "'Here we are now, entertain us'", a: "Smells Like Teen Spirit – Nirvana", options: ["Smells Like Teen Spirit – Nirvana", "Lithium – Nirvana", "Come as You Are – Nirvana", "In Bloom – Nirvana"] },
    { q: "'I want to ride my bicycle, I want to ride my bike'", a: "Bicycle Race – Queen", options: ["Bicycle Race – Queen", "Tour de France – Kraftwerk", "Daydream Believer – The Monkees", "Bohemian Rhapsody – Queen"] },
    { q: "'Du skal si' ka' du li' mansen, for mansen den ka' li' dig'", a: "Sig Du Ka' Li' Mansen – Bamses Venner", options: ["Sig Du Ka' Li' Mansen – Bamses Venner", "Vimmersvansen – Shu-bi-dua", "Langebansen – Gnags", "Bamse – Bamses Venner"] },
    { q: "'Imagine there's no heaven, it's easy if you try'", a: "Imagine – John Lennon", options: ["Imagine – John Lennon", "Let It Be – The Beatles", "Hey Jude – The Beatles", "Give Peace a Chance – John Lennon"] },
    { q: "'Is this love that I'm feeling?'", a: "Is This Love – Whitesnake", options: ["Is This Love – Whitesnake", "Is This Love – Bob Marley", "I Want to Know What Love Is – Foreigner", "What Is Love – Haddaway"] },
    { q: "'Every move you make, every bond you break'", a: "Every Breath You Take – The Police", options: ["Every Breath You Take – The Police", "I'll Be Watching You – Sting", "Roxanne – The Police", "Don't Stand So Close to Me – The Police"] },
    { q: "'I come from a land down under'", a: "Down Under – Men at Work", options: ["Down Under – Men at Work", "Waltzing Matilda – Traditional", "Beds Are Burning – Midnight Oil", "Working Class Man – Jimmy Barnes"] },
    { q: "'Today is gonna be the day that they're gonna throw it back to you'", a: "Wonderwall – Oasis", options: ["Wonderwall – Oasis", "Don't Look Back in Anger – Oasis", "Champagne Supernova – Oasis", "Bitter Sweet Symphony – The Verve"] },
    { q: "'Rabalderstræde — det strøg den ener, de ler og griner'", a: "Rabalderstræde – Gasolin'", options: ["Rabalderstræde – Gasolin'", "Kvinde Min – Gasolin'", "This Is My Life – Gasolin'", "Langebansen – Gnags"] },
    { q: "'We will, we will rock you!'", a: "We Will Rock You – Queen", options: ["We Will Rock You – Queen", "We Are the Champions – Queen", "Another One Bites the Dust – Queen", "Thunderstruck – AC/DC"] },
    { q: "'I'm a creep, I'm a weirdo'", a: "Creep – Radiohead", options: ["Creep – Radiohead", "Loser – Beck", "Basket Case – Green Day", "Paranoid Android – Radiohead"] },
    { q: "'You may say I'm a dreamer, but I'm not the only one'", a: "Imagine – John Lennon", options: ["Imagine – John Lennon", "Dream On – Aerosmith", "Dreamer – Supertramp", "Daydream Believer – The Monkees"] },
    { q: "'Nærmest lykkelig gik jeg ned ad gaden'", a: "Nærmest Lykkelig – TV-2", options: ["Nærmest Lykkelig – TV-2", "Elskere i Natten – Tøsedrengene", "Floden – Lars H.U.G.", "Sommer i Europa – Thomas Helmig"] },
    { q: "'SOS, please someone help me'", a: "SOS – ABBA", options: ["SOS – ABBA", "Help! – The Beatles", "Somebody to Love – Queen", "SOS – Rihanna"] },
    { q: "'What is love? Baby don't hurt me'", a: "What Is Love – Haddaway", options: ["What Is Love – Haddaway", "I Want to Know What Love Is – Foreigner", "Tainted Love – Soft Cell", "Crazy Little Thing Called Love – Queen"] },
    { q: "'On a dark desert highway, cool wind in my hair'", a: "Hotel California – Eagles", options: ["Hotel California – Eagles", "Desperado – Eagles", "Take It Easy – Eagles", "Peaceful Easy Feeling – Eagles"] },
    { q: "'And I would walk 500 miles'", a: "I'm Gonna Be (500 Miles) – The Proclaimers", options: ["I'm Gonna Be (500 Miles) – The Proclaimers", "Walk of Life – Dire Straits", "Walking on Sunshine – Katrina and the Waves", "Walk This Way – Aerosmith"] },
    { q: "'It's the final countdown!'", a: "The Final Countdown – Europe", options: ["The Final Countdown – Europe", "Jump – Van Halen", "Rock You Like a Hurricane – Scorpions", "Run to the Hills – Iron Maiden"] },
    { q: "'Somebody once told me the world is gonna roll me'", a: "All Star – Smash Mouth", options: ["All Star – Smash Mouth", "Walking on the Sun – Smash Mouth", "Tubthumping – Chumbawamba", "MMMBop – Hanson"] },
    { q: "'Under the bridge downtown, is where I drew some blood'", a: "Under the Bridge – Red Hot Chili Peppers", options: ["Under the Bridge – Red Hot Chili Peppers", "Californication – RHCP", "Give It Away – RHCP", "Scar Tissue – RHCP"] },
    { q: "'Mama, just killed a man, put a gun against his head'", a: "Bohemian Rhapsody – Queen", options: ["Bohemian Rhapsody – Queen", "The Show Must Go On – Queen", "I Want to Break Free – Queen", "Killer Queen – Queen"] },
    { q: "'I bless the rains down in Africa'", a: "Africa – Toto", options: ["Africa – Toto", "Rosanna – Toto", "In the Air Tonight – Phil Collins", "The Lion Sleeps Tonight – The Tokens"] },
    { q: "'Smuk som et stjerneskud — og jeg ta'r mit gode tøj på'", a: "Smuk Som Et Stjerneskud – Shu-bi-dua", options: ["Smuk Som Et Stjerneskud – Shu-bi-dua", "Det' Noget Med Ansen – Shu-bi-dua", "Sexchansen – Shu-bi-dua", "Supermarket – Shu-bi-dua"] },
    { q: "'I've got my mind set on you'", a: "Got My Mind Set on You – George Harrison", options: ["Got My Mind Set on You – George Harrison", "My Sweet Lord – George Harrison", "Let It Be – The Beatles", "Come Together – The Beatles"] }
  ],
  "One-Hit Wonders": [
    { q: "Hvem sang 'Take On Me' — var de one-hit wonders i USA?", a: "a-ha", options: ["a-ha", "Tears for Fears", "Men at Work", "Kajagoogoo"] },
    { q: "Hvem sang 'Tainted Love' i 1981?", a: "Soft Cell", options: ["Soft Cell", "Depeche Mode", "Erasure", "Yazoo"] },
    { q: "Hvem sang 'Come on Eileen'?", a: "Dexys Midnight Runners", options: ["Dexys Midnight Runners", "Madness", "The Specials", "The Smiths"] },
    { q: "Hvem sang 'Video Killed the Radio Star'?", a: "The Buggles", options: ["The Buggles", "Gary Numan", "Kraftwerk", "Devo"] },
    { q: "Hvem sang 'Mambo No. 5'?", a: "Lou Bega", options: ["Lou Bega", "Ricky Martin", "Enrique Iglesias", "Marc Anthony"] },
    { q: "Hvem sang '99 Luftballons'?", a: "Nena", options: ["Nena", "Nina Hagen", "Kraftwerk", "Falco"] },
    { q: "Hvem sang 'Macarena'?", a: "Los del Río", options: ["Los del Río", "Ricky Martin", "Shakira", "Enrique Iglesias"] },
    { q: "Hvem sang 'Who Let the Dogs Out'?", a: "Baha Men", options: ["Baha Men", "Crazy Town", "Smash Mouth", "LFO"] },
    { q: "Hvem sang 'Ice Ice Baby'?", a: "Vanilla Ice", options: ["Vanilla Ice", "MC Hammer", "Snow", "Kriss Kross"] },
    { q: "Hvem sang 'Tubthumping (I Get Knocked Down)'?", a: "Chumbawamba", options: ["Chumbawamba", "Spacehog", "Wheatus", "Lit"] },
    { q: "Hvem sang 'Breakfast at Tiffany's'?", a: "Deep Blue Something", options: ["Deep Blue Something", "Toad the Wet Sprocket", "Gin Blossoms", "Fastball"] },
    { q: "Hvem sang 'Steal My Sunshine'?", a: "Len", options: ["Len", "Fastball", "Lit", "Eagle-Eye Cherry"] },
    { q: "Hvem sang 'Teenage Dirtbag'?", a: "Wheatus", options: ["Wheatus", "Lit", "Blink-182", "Sum 41"] },
    { q: "Hvem sang 'Walking on Sunshine'?", a: "Katrina and the Waves", options: ["Katrina and the Waves", "Cyndi Lauper", "The Go-Go's", "Belinda Carlisle"] },
    { q: "Hvem sang 'Spirit in the Sky'?", a: "Norman Greenbaum", options: ["Norman Greenbaum", "Creedence Clearwater Revival", "The Byrds", "Steppenwolf"] },
    { q: "Hvem sang 'Blue (Da Ba Dee)'?", a: "Eiffel 65", options: ["Eiffel 65", "Aqua", "Vengaboys", "Toy-Box"] },
    { q: "Hvem sang 'Rock Me Amadeus'?", a: "Falco", options: ["Falco", "Nena", "Kraftwerk", "a-ha"] },
    { q: "Hvem sang 'Safety Dance'?", a: "Men Without Hats", options: ["Men Without Hats", "Devo", "Thomas Dolby", "Kajagoogoo"] },
    { q: "Hvem sang 'Somebody That I Used to Know'?", a: "Gotye", options: ["Gotye", "Foster the People", "Fun.", "Passion Pit"] },
    { q: "Hvem sang 'Crazy Town' — 'Butterfly'?", a: "Crazy Town", options: ["Crazy Town", "Papa Roach", "Limp Bizkit", "Incubus"] },
    { q: "Hvem sang 'Flagpole Sitta'?", a: "Harvey Danger", options: ["Harvey Danger", "Lit", "Fastball", "Spacehog"] },
    { q: "Hvem sang 'The Way'?", a: "Fastball", options: ["Fastball", "Third Eye Blind", "Matchbox Twenty", "Deep Blue Something"] },
    { q: "Hvem sang 'Funkytown'?", a: "Lipps Inc.", options: ["Lipps Inc.", "Kool & the Gang", "Earth, Wind & Fire", "Chic"] },
    { q: "Hvem sang 'In the Year 2525'?", a: "Zager and Evans", options: ["Zager and Evans", "The Buggles", "Gary Numan", "Devo"] },
    { q: "Hvem sang 'My Sharona'?", a: "The Knack", options: ["The Knack", "Blondie", "The Cars", "The Police"] },
    { q: "Hvem sang 'Stacy's Mom'?", a: "Fountains of Wayne", options: ["Fountains of Wayne", "Wheatus", "Blink-182", "Jimmy Eat World"] },
    { q: "Hvem sang 'Save Tonight'?", a: "Eagle-Eye Cherry", options: ["Eagle-Eye Cherry", "Jack Johnson", "Jason Mraz", "Ben Harper"] },
    { q: "Hvem sang 'Kung Fu Fighting'?", a: "Carl Douglas", options: ["Carl Douglas", "Hot Chocolate", "KC and the Sunshine Band", "The Trammps"] },
    { q: "Hvem sang 'Mickey'?", a: "Toni Basil", options: ["Toni Basil", "Cyndi Lauper", "Go-Go's", "The Bangles"] },
    { q: "Hvem sang 'Brimful of Asha'?", a: "Cornershop", options: ["Cornershop", "Chumbawamba", "Morcheeba", "Massive Attack"] },
    { q: "Hvem sang 'You Get What You Give'?", a: "New Radicals", options: ["New Radicals", "Semisonic", "Fastball", "Third Eye Blind"] }
  ],
  "70'er Disco & Funk": [
    { q: "Hvem sang 'Stayin' Alive'?", a: "Bee Gees", options: ["Bee Gees", "ABBA", "KC and the Sunshine Band", "Donna Summer"] },
    { q: "Hvilket band sang 'September'?", a: "Earth, Wind & Fire", options: ["Earth, Wind & Fire", "Kool & the Gang", "Chic", "The Commodores"] },
    { q: "Hvem sang 'I Will Survive'?", a: "Gloria Gaynor", options: ["Gloria Gaynor", "Donna Summer", "Diana Ross", "Sister Sledge"] },
    { q: "Hvilket band sang 'Le Freak'?", a: "Chic", options: ["Chic", "KC and the Sunshine Band", "Earth, Wind & Fire", "Bee Gees"] },
    { q: "Hvem sang 'Hot Stuff'?", a: "Donna Summer", options: ["Donna Summer", "Gloria Gaynor", "Diana Ross", "Cher"] },
    { q: "Hvilket band sang 'Dancing Queen'?", a: "ABBA", options: ["ABBA", "Bee Gees", "Boney M", "The Carpenters"] },
    { q: "Hvem sang 'Superstition'?", a: "Stevie Wonder", options: ["Stevie Wonder", "James Brown", "Marvin Gaye", "Curtis Mayfield"] },
    { q: "Hvilket band sang 'Get Up (I Feel Like Being a) Sex Machine'?", a: "James Brown", options: ["James Brown", "Parliament", "Sly & the Family Stone", "Earth, Wind & Fire"] },
    { q: "Hvem sang 'Rasputin'?", a: "Boney M", options: ["Boney M", "ABBA", "Bee Gees", "Village People"] },
    { q: "Hvilket band sang 'Y.M.C.A.'?", a: "Village People", options: ["Village People", "Bee Gees", "Boney M", "Chic"] },
    { q: "Hvem sang 'Disco Inferno'?", a: "The Trammps", options: ["The Trammps", "Kool & the Gang", "KC and the Sunshine Band", "Bee Gees"] },
    { q: "Hvilket band sang 'That's the Way (I Like It)'?", a: "KC and the Sunshine Band", options: ["KC and the Sunshine Band", "Bee Gees", "Earth, Wind & Fire", "Kool & the Gang"] },
    { q: "Hvem sang 'We Are Family'?", a: "Sister Sledge", options: ["Sister Sledge", "The Pointer Sisters", "Chic", "En Vogue"] },
    { q: "Hvilket band sang 'Celebration'?", a: "Kool & the Gang", options: ["Kool & the Gang", "Earth, Wind & Fire", "KC and the Sunshine Band", "Chic"] },
    { q: "Hvem sang 'What's Going On'?", a: "Marvin Gaye", options: ["Marvin Gaye", "Stevie Wonder", "Curtis Mayfield", "Al Green"] },
    { q: "Hvilket band sang 'Play That Funky Music'?", a: "Wild Cherry", options: ["Wild Cherry", "KC and the Sunshine Band", "Parliament", "Ohio Players"] },
    { q: "Hvem sang 'I Feel Love'?", a: "Donna Summer", options: ["Donna Summer", "Gloria Gaynor", "Grace Jones", "Blondie"] },
    { q: "Hvilket band sang 'Give Up the Funk (Tear the Roof off the Sucker)'?", a: "Parliament", options: ["Parliament", "Funkadelic", "Earth, Wind & Fire", "James Brown"] },
    { q: "Hvem sang 'Let's Get It On'?", a: "Marvin Gaye", options: ["Marvin Gaye", "Barry White", "Al Green", "Teddy Pendergrass"] },
    { q: "Hvilket band sang 'Waterloo'?", a: "ABBA", options: ["ABBA", "Boney M", "Bee Gees", "Blondie"] },
    { q: "Hvem sang 'Shaft' (temasangen)?", a: "Isaac Hayes", options: ["Isaac Hayes", "Curtis Mayfield", "James Brown", "Barry White"] },
    { q: "Hvilket band sang 'Brick House'?", a: "The Commodores", options: ["The Commodores", "Earth, Wind & Fire", "Kool & the Gang", "Ohio Players"] },
    { q: "Hvem sang 'Car Wash'?", a: "Rose Royce", options: ["Rose Royce", "The Trammps", "KC and the Sunshine Band", "Wild Cherry"] },
    { q: "Hvilket band sang 'Heart of Glass'?", a: "Blondie", options: ["Blondie", "The Go-Go's", "Donna Summer", "Grace Jones"] },
    { q: "Hvem sang 'Night Fever'?", a: "Bee Gees", options: ["Bee Gees", "ABBA", "Donna Summer", "KC and the Sunshine Band"] },
    { q: "Hvilket band sang 'Boogie Wonderland'?", a: "Earth, Wind & Fire", options: ["Earth, Wind & Fire", "Chic", "Bee Gees", "Kool & the Gang"] },
    { q: "Hvem sang 'Rivers of Babylon'?", a: "Boney M", options: ["Boney M", "Bob Marley", "Jimmy Cliff", "UB40"] },
    { q: "Hvilket band sang 'Good Times'?", a: "Chic", options: ["Chic", "Kool & the Gang", "Earth, Wind & Fire", "The Commodores"] },
    { q: "Hvem sang 'You Should Be Dancing'?", a: "Bee Gees", options: ["Bee Gees", "Donna Summer", "KC and the Sunshine Band", "Gloria Gaynor"] },
    { q: "Hvilket band sang 'Ring My Bell'?", a: "Anita Ward", options: ["Anita Ward", "Donna Summer", "Gloria Gaynor", "Sister Sledge"] },
    { q: "Hvem sang 'Le Freak, c'est chic'?", a: "Chic", options: ["Chic", "Bee Gees", "Donna Summer", "Village People"] }
  ],
  "Hvem Er Bandet?": [
    { q: "Mick Jagger er forsanger i hvilket band?", a: "The Rolling Stones", options: ["The Rolling Stones", "The Beatles", "Led Zeppelin", "The Who"] },
    { q: "Bono er forsanger i hvilket band?", a: "U2", options: ["Coldplay", "U2", "R.E.M.", "The Verve"] },
    { q: "Freddie Mercury var forsanger i?", a: "Queen", options: ["Queen", "Led Zeppelin", "The Who", "Pink Floyd"] },
    { q: "Kurt Cobain var forsanger i?", a: "Nirvana", options: ["Pearl Jam", "Nirvana", "Soundgarden", "Alice in Chains"] },
    { q: "Axl Rose er forsanger i?", a: "Guns N' Roses", options: ["Guns N' Roses", "Mötley Crüe", "Poison", "Def Leppard"] },
    { q: "Robert Plant var forsanger i?", a: "Led Zeppelin", options: ["Led Zeppelin", "Deep Purple", "Black Sabbath", "The Who"] },
    { q: "Dave Grohl var trommeslager i Nirvana — hvilket band startede han derefter?", a: "Foo Fighters", options: ["Foo Fighters", "Queens of the Stone Age", "Them Crooked Vultures", "Audioslave"] },
    { q: "Lars Ulrich er trommeslager i?", a: "Metallica", options: ["Metallica", "Megadeth", "Slayer", "Anthrax"] },
    { q: "Roger Waters var bassist og sangskriver i?", a: "Pink Floyd", options: ["Pink Floyd", "Genesis", "Yes", "King Crimson"] },
    { q: "Ozzy Osbourne var forsanger i?", a: "Black Sabbath", options: ["Black Sabbath", "Deep Purple", "Judas Priest", "Iron Maiden"] },
    { q: "Kim Larsen var forsanger i hvilket tidligt dansk band?", a: "Gasolin'", options: ["Gasolin'", "Shu-bi-dua", "Gnags", "Sort Sol"] },
    { q: "Thom Yorke er forsanger i?", a: "Radiohead", options: ["Radiohead", "Muse", "Coldplay", "Arctic Monkeys"] },
    { q: "Liam Gallagher er forsanger i?", a: "Oasis", options: ["Blur", "Oasis", "Pulp", "The Verve"] },
    { q: "Bruce Dickinson er forsanger i?", a: "Iron Maiden", options: ["Iron Maiden", "Judas Priest", "Motörhead", "Saxon"] },
    { q: "Anthony Kiedis er forsanger i?", a: "Red Hot Chili Peppers", options: ["Red Hot Chili Peppers", "Rage Against the Machine", "Jane's Addiction", "Primus"] },
    { q: "Jon Bon Jovi er forsanger i?", a: "Bon Jovi", options: ["Bon Jovi", "Def Leppard", "Whitesnake", "Journey"] },
    { q: "Chris Martin er forsanger i?", a: "Coldplay", options: ["Coldplay", "Radiohead", "Keane", "Snow Patrol"] },
    { q: "Eddie Vedder er forsanger i?", a: "Pearl Jam", options: ["Pearl Jam", "Nirvana", "Soundgarden", "Temple of the Dog"] },
    { q: "Angus Young spiller guitar i?", a: "AC/DC", options: ["AC/DC", "Motörhead", "Judas Priest", "Iron Maiden"] },
    { q: "Steffen Brandt er forsanger i?", a: "TV-2", options: ["TV-2", "Tøsedrengene", "Gnags", "Kashmir"] },
    { q: "Jesper Binzer er forsanger i?", a: "D-A-D", options: ["D-A-D", "Volbeat", "Pretty Maids", "Sort Sol"] },
    { q: "Michael Poulsen er forsanger i?", a: "Volbeat", options: ["Volbeat", "D-A-D", "Pretty Maids", "Dizzy Mizz Lizzy"] },
    { q: "Matt Bellamy er forsanger i?", a: "Muse", options: ["Muse", "Radiohead", "Coldplay", "Placebo"] },
    { q: "Robert Smith er forsanger i?", a: "The Cure", options: ["The Cure", "Siouxsie and the Banshees", "Joy Division", "Bauhaus"] },
    { q: "Sting var forsanger i?", a: "The Police", options: ["The Police", "Dire Straits", "U2", "Talking Heads"] },
    { q: "Dave Gahan er forsanger i?", a: "Depeche Mode", options: ["Depeche Mode", "New Order", "Pet Shop Boys", "Erasure"] },
    { q: "Michael Stipe var forsanger i?", a: "R.E.M.", options: ["R.E.M.", "The Smiths", "U2", "Talking Heads"] },
    { q: "Phil Collins var forsanger og trommeslager i?", a: "Genesis", options: ["Genesis", "Pink Floyd", "Yes", "King Crimson"] },
    { q: "Mark Knopfler var forsanger og guitarist i?", a: "Dire Straits", options: ["Dire Straits", "The Police", "U2", "Talking Heads"] },
    { q: "Joey Ramone var forsanger i?", a: "Ramones", options: ["Ramones", "The Clash", "Sex Pistols", "Blondie"] },
    { q: "Debbie Harry var forsanger i?", a: "Blondie", options: ["Blondie", "The Go-Go's", "The Pretenders", "Siouxsie and the Banshees"] }
  ],
  "2000'er & Nyere": [
    { q: "Hvem sang 'Crazy in Love' i 2003?", a: "Beyoncé", options: ["Beyoncé", "Rihanna", "Alicia Keys", "Christina Aguilera"] },
    { q: "Hvilket band sang 'Mr. Brightside'?", a: "The Killers", options: ["The Killers", "Arctic Monkeys", "Franz Ferdinand", "Bloc Party"] },
    { q: "Hvem sang 'Rolling in the Deep'?", a: "Adele", options: ["Adele", "Amy Winehouse", "Florence Welch", "Duffy"] },
    { q: "Hvilket band sang 'I Bet You Look Good on the Dancefloor'?", a: "Arctic Monkeys", options: ["Arctic Monkeys", "The Killers", "Franz Ferdinand", "Kaiser Chiefs"] },
    { q: "Hvem sang 'Rehab'?", a: "Amy Winehouse", options: ["Amy Winehouse", "Adele", "Duffy", "Lily Allen"] },
    { q: "Hvilket band sang 'Clocks'?", a: "Coldplay", options: ["Coldplay", "Keane", "Snow Patrol", "Travis"] },
    { q: "Hvem sang 'Poker Face'?", a: "Lady Gaga", options: ["Lady Gaga", "Katy Perry", "Rihanna", "Ke$ha"] },
    { q: "Hvilket band sang 'Seven Nation Army'?", a: "The White Stripes", options: ["The White Stripes", "The Black Keys", "The Strokes", "Queens of the Stone Age"] },
    { q: "Hvem sang 'Umbrella'?", a: "Rihanna", options: ["Rihanna", "Beyoncé", "Alicia Keys", "Lady Gaga"] },
    { q: "Hvilket band sang 'Chop Suey!'?", a: "System of a Down", options: ["System of a Down", "Slipknot", "Korn", "Linkin Park"] },
    { q: "Hvem sang 'Get Lucky'?", a: "Daft Punk ft. Pharrell Williams", options: ["Daft Punk ft. Pharrell Williams", "Calvin Harris", "David Guetta", "Avicii"] },
    { q: "Hvilket band sang 'In the End'?", a: "Linkin Park", options: ["Linkin Park", "Limp Bizkit", "Papa Roach", "Evanescence"] },
    { q: "Hvem sang 'Uptown Funk'?", a: "Mark Ronson ft. Bruno Mars", options: ["Mark Ronson ft. Bruno Mars", "Justin Timberlake", "Pharrell Williams", "Jason Derulo"] },
    { q: "Hvilket band sang 'Somebody Told Me'?", a: "The Killers", options: ["The Killers", "Arctic Monkeys", "Franz Ferdinand", "The Strokes"] },
    { q: "Hvem sang 'Shape of You'?", a: "Ed Sheeran", options: ["Ed Sheeran", "Sam Smith", "James Bay", "Shawn Mendes"] },
    { q: "Hvilket band sang 'Take Me Out'?", a: "Franz Ferdinand", options: ["Franz Ferdinand", "The Killers", "Arctic Monkeys", "Interpol"] },
    { q: "Hvem sang 'Bad Guy'?", a: "Billie Eilish", options: ["Billie Eilish", "Lorde", "Halsey", "Dua Lipa"] },
    { q: "Hvilket band sang 'Use Somebody'?", a: "Kings of Leon", options: ["Kings of Leon", "The Killers", "Coldplay", "Muse"] },
    { q: "Hvem sang 'Blinding Lights'?", a: "The Weeknd", options: ["The Weeknd", "Bruno Mars", "Daft Punk", "Calvin Harris"] },
    { q: "Hvilket band sang 'Do I Wanna Know?'?", a: "Arctic Monkeys", options: ["Arctic Monkeys", "The Black Keys", "Tame Impala", "Royal Blood"] },
    { q: "Hvem sang 'Someone Like You'?", a: "Adele", options: ["Adele", "Sam Smith", "Amy Winehouse", "Lana Del Rey"] },
    { q: "Hvilket band sang 'Feel Good Inc.'?", a: "Gorillaz", options: ["Gorillaz", "Blur", "Radiohead", "Massive Attack"] },
    { q: "Hvem sang 'Hips Don't Lie'?", a: "Shakira", options: ["Shakira", "Jennifer Lopez", "Beyoncé", "Rihanna"] },
    { q: "Hvilket band sang 'Radioactive'?", a: "Imagine Dragons", options: ["Imagine Dragons", "OneRepublic", "Bastille", "Twenty One Pilots"] },
    { q: "Hvem sang 'Levitating'?", a: "Dua Lipa", options: ["Dua Lipa", "Lizzo", "Doja Cat", "Ariana Grande"] },
    { q: "Hvilket band sang 'Stressed Out'?", a: "Twenty One Pilots", options: ["Twenty One Pilots", "Imagine Dragons", "Bastille", "Panic! at the Disco"] },
    { q: "Hvem sang 'Royals'?", a: "Lorde", options: ["Lorde", "Billie Eilish", "Halsey", "Lana Del Rey"] },
    { q: "Hvilket band sang 'The Pretender'?", a: "Foo Fighters", options: ["Foo Fighters", "Queens of the Stone Age", "Muse", "Green Day"] },
    { q: "Hvem sang 'Old Town Road'?", a: "Lil Nas X", options: ["Lil Nas X", "Post Malone", "Travis Scott", "Drake"] },
    { q: "Hvilket band sang 'Pompeii'?", a: "Bastille", options: ["Bastille", "Imagine Dragons", "Twenty One Pilots", "OneRepublic"] },
    { q: "Hvem sang 'Wake Me Up'?", a: "Avicii", options: ["Avicii", "David Guetta", "Calvin Harris", "Tiësto"] }
  ],
  "Album Covers": [
    { q: "Hvilket albums cover viser et prisme der spreder lys i en regnbue?", a: "The Dark Side of the Moon – Pink Floyd", options: ["The Dark Side of the Moon – Pink Floyd", "Wish You Were Here – Pink Floyd", "Abbey Road – The Beatles", "Houses of the Holy – Led Zeppelin"] },
    { q: "Hvilket album har fire personer der krydser en fodgængerovergang?", a: "Abbey Road – The Beatles", options: ["Abbey Road – The Beatles", "Let It Be – The Beatles", "The Dark Side of the Moon – Pink Floyd", "London Calling – The Clash"] },
    { q: "Hvilket album viser en brændende mand der giver hånd?", a: "Wish You Were Here – Pink Floyd", options: ["Wish You Were Here – Pink Floyd", "The Dark Side of the Moon – Pink Floyd", "The Wall – Pink Floyd", "Animals – Pink Floyd"] },
    { q: "Hvilket album viser en baby der svømmer efter en dollarseddel?", a: "Nevermind – Nirvana", options: ["Nevermind – Nirvana", "In Utero – Nirvana", "Ten – Pearl Jam", "Bleach – Nirvana"] },
    { q: "Hvilket album har en banan på coveret (Andy Warhol design)?", a: "The Velvet Underground & Nico", options: ["The Velvet Underground & Nico", "Sticky Fingers – The Rolling Stones", "Yellow Submarine – The Beatles", "Banana – The Dandy Warhols"] },
    { q: "Hvilket album viser en stor mund med tungen ude (logo)?", a: "Sticky Fingers – The Rolling Stones", options: ["Sticky Fingers – The Rolling Stones", "Let It Bleed – The Rolling Stones", "Exile on Main St. – The Rolling Stones", "Some Girls – The Rolling Stones"] },
    { q: "Hvilket album viser en Hindenburg-luftskib i flammer?", a: "Led Zeppelin I", options: ["Led Zeppelin I", "Led Zeppelin II", "Physical Graffiti – Led Zeppelin", "Houses of the Holy – Led Zeppelin"] },
    { q: "Hvilket album viser en mur af hvide mursten?", a: "The Wall – Pink Floyd", options: ["The Wall – Pink Floyd", "Another Brick in the Wall – Pink Floyd", "The Dark Side of the Moon – Pink Floyd", "Animals – Pink Floyd"] },
    { q: "Hvilket albums cover er helt sort med kun bandets navn i sort-på-sort?", a: "The Black Album – Metallica", options: ["The Black Album – Metallica", "Back in Black – AC/DC", "Blackout – Scorpions", "Black Sabbath – Black Sabbath"] },
    { q: "Hvilket album viser en kvinde der hæver armen med lyn og energi?", a: "Nevermind the Bollocks – Sex Pistols", options: ["Nevermind the Bollocks – Sex Pistols", "Parallel Lines – Blondie", "Horses – Patti Smith", "Nevermind – Nirvana"] },
    { q: "Hvilket album har en jæt-sort-hvid foto af en kvinde i hvid skjorte?", a: "Horses – Patti Smith", options: ["Horses – Patti Smith", "Easter – Patti Smith", "Parallel Lines – Blondie", "Pretenders – The Pretenders"] },
    { q: "Hvilket album viser en ko?", a: "Atom Heart Mother – Pink Floyd", options: ["Atom Heart Mother – Pink Floyd", "Aqualung – Jethro Tull", "Band on the Run – Wings", "Harvest – Neil Young"] },
    { q: "Hvilket Led Zeppelin-album viser luftskibet Hindenburg i flammer på coveret?", a: "Led Zeppelin I", options: ["Led Zeppelin I", "Led Zeppelin II", "Houses of the Holy", "Physical Graffiti"] },
    { q: "Hvilket album viser 4 symboler i stedet for titel/bandnavn?", a: "Led Zeppelin IV", options: ["Led Zeppelin IV", "Led Zeppelin III", "Houses of the Holy", "Physical Graffiti"] },
    { q: "Hvilket album har Sgt. Pepper-kostumet og en stor flok berømtheder?", a: "Sgt. Pepper's Lonely Hearts Club Band – The Beatles", options: ["Sgt. Pepper's Lonely Hearts Club Band – The Beatles", "Abbey Road – The Beatles", "Magical Mystery Tour – The Beatles", "Let It Be – The Beatles"] },
    { q: "Hvilket album viser en mand i ild på scenen?", a: "Live After Death – Iron Maiden", options: ["Live After Death – Iron Maiden", "Made in Japan – Deep Purple", "Alive! – Kiss", "Frampton Comes Alive – Peter Frampton"] },
    { q: "Hvilket Weezer-album er kendt som 'The Blue Album' med et lyseblåt cover?", a: "Weezer (Blue Album)", options: ["Weezer (Blue Album)", "Weezer (Green Album)", "Weezer (Red Album)", "Weezer (White Album)"] },
    { q: "Hvilket album viser et ur der smelter (Dalí-inspireret)?", a: "The Persistence of Memory er et maleri - men hvilket rockalbum bruger et ur?", options: ["Clockwork Angels – Rush", "Time – Electric Light Orchestra", "A Clockwork Orange Soundtrack", "Time Flies – Oasis"] },
    { q: "Hvilket album har et cover med mønster af sorte og hvide kors?", a: "Closer – Joy Division", options: ["Closer – Joy Division", "Unknown Pleasures – Joy Division", "Power, Corruption & Lies – New Order", "Disintegration – The Cure"] },
    { q: "Hvilket albums cover viser sorte bølgeformer (pulsar-signal)?", a: "Unknown Pleasures – Joy Division", options: ["Unknown Pleasures – Joy Division", "Closer – Joy Division", "Music for the Masses – Depeche Mode", "Kid A – Radiohead"] },
    { q: "Hvilket album har en pige med en rød ballon?", a: "Banksy er kunstner - men hvilket albums cover viser en ballon?", options: ["Nena – 99 Luftballons", "The Wall – Pink Floyd", "Banksy's Cover Art", "Coldplay – A Rush of Blood to the Head"] },
    { q: "Hvilket album viser en strand-scene med et flyende gris?", a: "Animals – Pink Floyd", options: ["Animals – Pink Floyd", "Wish You Were Here – Pink Floyd", "Atom Heart Mother – Pink Floyd", "A Momentary Lapse of Reason – Pink Floyd"] },
    { q: "Hvilket bands selvtitlede dobbeltalbum fra 1968 er kendt som 'The White Album'?", a: "The Beatles", options: ["The Beatles", "Metallica", "Weezer", "The Velvet Underground"] },
    { q: "Hvilket album viser en trekantet arkitektur i orange/rødt?", a: "Screaming for Vengeance – Judas Priest", options: ["Screaming for Vengeance – Judas Priest", "Ride the Lightning – Metallica", "Master of Puppets – Metallica", "Iron Fist – Motörhead"] },
    { q: "Hvilket album har et cover med en nøgen baby der svømmer mod en dollarseddel under vand?", a: "Nevermind – Nirvana", options: ["Nevermind – Nirvana", "Ten – Pearl Jam", "Superunknown – Soundgarden", "In Utero – Nirvana"] },
    { q: "Hvilket album viser et øje og en pyramide?", a: "Eye in the Sky – The Alan Parsons Project", options: ["Eye in the Sky – The Alan Parsons Project", "The Dark Side of the Moon – Pink Floyd", "Pyramid – The Alan Parsons Project", "All Seeing Eye – Asia"] },
    { q: "Hvilket album har et cover med en mand der sidder alene ved et bord med stjerner?", a: "Breakfast in America – Supertramp", options: ["Breakfast in America – Supertramp", "Crime of the Century – Supertramp", "Brothers in Arms – Dire Straits", "Aja – Steely Dan"] },
    { q: "Hvilket album viser en guitar i blåt neon-lys?", a: "Brothers in Arms – Dire Straits", options: ["Brothers in Arms – Dire Straits", "Sultans of Swing – Dire Straits", "Money for Nothing – Dire Straits", "Love Over Gold – Dire Straits"] },
    { q: "Hvilket album har et Andy Warhol-designet cover med en ægte lynlås på et par jeans?", a: "Sticky Fingers – The Rolling Stones", options: ["Sticky Fingers – The Rolling Stones", "Exile on Main St. – The Rolling Stones", "Loaded – The Velvet Underground", "Aladdin Sane – David Bowie"] },
    { q: "Hvilket album viser et 'OK Computer' motorvejs-landskab?", a: "OK Computer – Radiohead", options: ["OK Computer – Radiohead", "The Bends – Radiohead", "Kid A – Radiohead", "Hail to the Thief – Radiohead"] },
    { q: "Hvilket album viser King Kong på en bygning med et fly?", a: "News of the World – Queen", options: ["News of the World – Queen", "A Night at the Opera – Queen", "Sheer Heart Attack – Queen", "Jazz – Queen"] }
  ],
  "Årtier Mix": [
    { q: "Hvem havde det bedst sælgende album nogensinde med 'Thriller'?", a: "Michael Jackson", options: ["Michael Jackson", "The Beatles", "Elvis Presley", "Elton John"] },
    { q: "Hvilket instrument er Keith Richards mest kendt for at spille?", a: "Guitar", options: ["Guitar", "Bas", "Keyboard", "Trommer"] },
    { q: "Hvem skrev 'Bridge over Troubled Water'?", a: "Simon & Garfunkel", options: ["Simon & Garfunkel", "The Beatles", "Elton John", "Cat Stevens"] },
    { q: "Hvilket land kommer ABBA fra?", a: "Sverige", options: ["Sverige", "Norge", "Danmark", "Finland"] },
    { q: "Hvem er 'The King of Rock and Roll'?", a: "Elvis Presley", options: ["Elvis Presley", "Chuck Berry", "Little Richard", "Jerry Lee Lewis"] },
    { q: "Hvem var trommeslager i Cream sammen med Eric Clapton og Jack Bruce?", a: "Ginger Baker", options: ["Ginger Baker", "John Bonham", "Keith Moon", "Mick Fleetwood"] },
    { q: "Hvem sang 'Hallelujah' (original)?", a: "Leonard Cohen", options: ["Jeff Buckley", "Leonard Cohen", "Bob Dylan", "Rufus Wainwright"] },
    { q: "Hvilket år blev MTV lanceret?", a: "1981", options: ["1979", "1981", "1983", "1985"] },
    { q: "Hvem havde i 2024 Spotifys mest streamede sang nogensinde med 'Blinding Lights'?", a: "The Weeknd", options: ["The Weeknd", "Drake", "Ed Sheeran", "Bad Bunny"] },
    { q: "Hvilket band opfandt begrebet 'heavy metal'?", a: "Black Sabbath", options: ["Black Sabbath", "Led Zeppelin", "Deep Purple", "Judas Priest"] },
    { q: "Hvem sang 'Respect' (mest kendte version)?", a: "Aretha Franklin", options: ["Aretha Franklin", "Otis Redding", "Tina Turner", "Diana Ross"] },
    { q: "Hvilket instrument spillede Jimi Hendrix?", a: "Guitar", options: ["Guitar", "Bas", "Trommer", "Keyboard"] },
    { q: "Hvem er kendt som 'Queen of Pop'?", a: "Madonna", options: ["Madonna", "Whitney Houston", "Beyoncé", "Janet Jackson"] },
    { q: "Hvilket band tog sit navn fra en blytung luftskib-joke?", a: "Led Zeppelin", options: ["Led Zeppelin", "Iron Maiden", "Iron Butterfly", "Black Sabbath"] },
    { q: "Hvem havde det berømte Woodstock-nummer med 'Star-Spangled Banner' på guitar?", a: "Jimi Hendrix", options: ["Jimi Hendrix", "Janis Joplin", "The Who", "Santana"] },
    { q: "Hvem er forsanger i Tøsedrengene?", a: "Michael Falch", options: ["Michael Falch", "Steffen Brandt", "Kim Larsen", "Lars H.U.G."] },
    { q: "Hvilken by er Beatles fra?", a: "Liverpool", options: ["Liverpool", "London", "Manchester", "Birmingham"] },
    { q: "Hvem producerede Michael Jacksons 'Thriller'-album?", a: "Quincy Jones", options: ["Quincy Jones", "Phil Spector", "Rick Rubin", "Dr. Dre"] },
    { q: "Hvilket band hed oprindeligt 'Smile' før de skiftede navn?", a: "Queen", options: ["Queen", "Genesis", "Pink Floyd", "The Police"] },
    { q: "Hvilket dansk-norsk band sang 'Barbie Girl' fra 1997?", a: "Aqua", options: ["Aqua", "Ace of Base", "S Club 7", "Vengaboys"] },
    { q: "Hvem er den mest vindende kunstner ved Grammy Awards?", a: "Beyoncé", options: ["Beyoncé", "Georg Solti", "Quincy Jones", "Stevie Wonder"] },
    { q: "Hvilket instrument spillede Elton John som sit primære?", a: "Klaver", options: ["Klaver", "Guitar", "Saxofon", "Trommer"] },
    { q: "Hvem startede Motown Records?", a: "Berry Gordy", options: ["Berry Gordy", "Phil Spector", "Quincy Jones", "Sam Cooke"] },
    { q: "Hvilket band spillede på taget af Apple Corps i London i 1969?", a: "The Beatles", options: ["The Beatles", "The Rolling Stones", "The Who", "Led Zeppelin"] },
    { q: "Hvad hedder Tommy Seebachs mest kendte sang?", a: "Krøller eller ej", options: ["Krøller eller ej", "Apache", "Under Stjernerne", "Hip Hurra"] },
    { q: "Hvem har solgt flest albums globalt?", a: "The Beatles", options: ["The Beatles", "Elvis Presley", "Michael Jackson", "Elton John"] },
    { q: "Hvilket år blev 'Smells Like Teen Spirit' udgivet?", a: "1991", options: ["1989", "1991", "1993", "1994"] },
    { q: "Hvem designede det berømte Rolling Stones-tungelogo?", a: "John Pasche", options: ["John Pasche", "Andy Warhol", "Peter Blake", "Storm Thorgerson"] },
    { q: "Hvem var den første kvinde optaget i Rock and Roll Hall of Fame?", a: "Aretha Franklin", options: ["Aretha Franklin", "Janis Joplin", "Tina Turner", "Madonna"] },
    { q: "Hvilket band havde det længste koncert-residency i Las Vegas?", a: "Elton John", options: ["Elton John", "Celine Dion", "Britney Spears", "Cher"] },
    { q: "Hvem sang 'Somebody to Love' — Queen eller Jefferson Airplane?", a: "Begge!", options: ["Begge!", "Kun Queen", "Kun Jefferson Airplane", "Ingen af dem"] }
  ],
  "Palles kategori": [
    { q: "Hvem sang 'Beat It' i 1982?", a: "Michael Jackson", options: ["Michael Jackson", "Prince", "Lionel Richie", "Stevie Wonder"] },
    { q: "Hvilket band sang 'Hungry Like the Wolf'?", a: "Duran Duran", options: ["Duran Duran", "Spandau Ballet", "Culture Club", "ABC"] },
    { q: "Hvem sang 'Time After Time' i 1984?", a: "Cyndi Lauper", options: ["Cyndi Lauper", "Madonna", "Whitney Houston", "Pat Benatar"] },
    { q: "Hvem sang 'Material Girl'?", a: "Madonna", options: ["Madonna", "Cyndi Lauper", "Janet Jackson", "Tina Turner"] },
    { q: "Hvilket band sang 'Sweet Dreams (Are Made of This)'?", a: "Eurythmics", options: ["Eurythmics", "Pet Shop Boys", "Yazoo", "Soft Cell"] },
    { q: "Hvem sang 'Walking on Sunshine' i 1985?", a: "Katrina and the Waves", options: ["Katrina and the Waves", "Bananarama", "The Bangles", "Belinda Carlisle"] },
    { q: "Hvilket band sang 'Don't You Want Me'?", a: "The Human League", options: ["The Human League", "Soft Cell", "Heaven 17", "Yazoo"] },
    { q: "Hvem sang 'Total Eclipse of the Heart'?", a: "Bonnie Tyler", options: ["Bonnie Tyler", "Tina Turner", "Pat Benatar", "Stevie Nicks"] },
    { q: "Hvem sang 'Take My Breath Away' fra Top Gun?", a: "Berlin", options: ["Berlin", "Heart", "Pat Benatar", "Survivor"] },
    { q: "Hvem sang 'Danger Zone' fra Top Gun?", a: "Kenny Loggins", options: ["Kenny Loggins", "Glenn Frey", "Bryan Adams", "Bob Seger"] },
    { q: "Hvilket band sang 'Walk Like an Egyptian'?", a: "The Bangles", options: ["The Bangles", "Bananarama", "Go-Go's", "Belinda Carlisle"] },
    { q: "Hvem sang 'Maneater' i 1982?", a: "Hall & Oates", options: ["Hall & Oates", "Toto", "Foreigner", "Survivor"] },
    { q: "Hvilket Queen-nummer havde en berømt drag-musikvideo med støvsugning?", a: "I Want to Break Free", options: ["I Want to Break Free", "Radio Ga Ga", "It's a Hard Life", "One Vision"] },
    { q: "Hvem sang 'Let's Dance' i 1983?", a: "David Bowie", options: ["David Bowie", "Mick Jagger", "Bryan Ferry", "Roxy Music"] },
    { q: "Hvilket dansk gruppe stod bag 'Sunshine Reggae'?", a: "Laid Back", options: ["Laid Back", "Bamses Venner", "Shu-bi-dua", "TV-2"] },
    { q: "Hvem sang 'Bakerman'?", a: "Laid Back", options: ["Laid Back", "Sneakers", "Sort Sol", "Anne Linnet"] },
    { q: "Hvilket TV-2-album indeholder 'Bag Duggede Ruder'?", a: "Nærmest Lykkelig", options: ["Nærmest Lykkelig", "Verden Er Vidunderlig", "Beat", "Yndlingsbabe"] },
    { q: "Hvem sang 'Tusind Stykker'?", a: "Anne Linnet", options: ["Anne Linnet", "Sanne Salomonsen", "Lis Sørensen", "Lone Kellermann"] },
    { q: "Hvem sang 'I'm Still Standing'?", a: "Elton John", options: ["Elton John", "Phil Collins", "Billy Joel", "George Michael"] },
    { q: "Hvem sang titelnummeret til filmen 'Footloose'?", a: "Kenny Loggins", options: ["Kenny Loggins", "Bonnie Tyler", "Bryan Adams", "Huey Lewis"] },
    { q: "Hvilket svensk duo sang 'The Look' i 1989?", a: "Roxette", options: ["Roxette", "Ace of Base", "ABBA", "Europe"] },
    { q: "Hvilket band sang 'Manic Monday' (skrevet af Prince)?", a: "The Bangles", options: ["The Bangles", "Bananarama", "Go-Go's", "Belinda Carlisle"] },
    { q: "Hvem sang 'Cruel Summer' i 1983?", a: "Bananarama", options: ["Bananarama", "The Bangles", "Wham!", "Spandau Ballet"] },
    { q: "Hvilket band sang 'Eternal Flame'?", a: "The Bangles", options: ["The Bangles", "Bananarama", "Heart", "Wilson Phillips"] },
    { q: "Hvem sang 'Joe le Taxi' som 14-årig i 1987?", a: "Vanessa Paradis", options: ["Vanessa Paradis", "France Gall", "Mylène Farmer", "Dalida"] },
    { q: "Hvilket fransk synth-pop hit fra 1986 har et ikonisk kor 'Voyage, voyage'?", a: "Voyage Voyage – Desireless", options: ["Voyage Voyage – Desireless", "Joe le Taxi – Vanessa Paradis", "Magic Fly – Space", "Pop Muzik – M"] },
    { q: "Hvem sang 'Rosanna' i 1982?", a: "Toto", options: ["Toto", "Journey", "Foreigner", "REO Speedwagon"] },
    { q: "Hvilket charity-projekt udgav 'We Are the World' i 1985?", a: "USA for Africa", options: ["USA for Africa", "Band Aid", "Live Aid", "Hear 'n Aid"] },
    { q: "Hvilket Madonna-album fra 1986 indeholder 'La Isla Bonita'?", a: "True Blue", options: ["True Blue", "Like a Virgin", "Madonna", "Who's That Girl"] },
    { q: "Hvem sang 'Don't Worry Be Happy' i 1988?", a: "Bobby McFerrin", options: ["Bobby McFerrin", "Lionel Richie", "Stevie Wonder", "Al Jarreau"] }
  ],
  "ABBA": [
    { q: "Hvilket land kommer ABBA fra?", a: "Sverige", options: ["Sverige", "Norge", "Danmark", "Finland"] },
    { q: "Hvilket år vandt ABBA Eurovision Song Contest?", a: "1974", options: ["1972", "1974", "1976", "1978"] },
    { q: "Hvilken sang vandt Eurovision for ABBA?", a: "Waterloo", options: ["Waterloo", "SOS", "Mamma Mia", "Ring Ring"] },
    { q: "Hvor mange medlemmer havde ABBA?", a: "4", options: ["3", "4", "5", "6"] },
    { q: "Hvilken by er ABBA fra?", a: "Stockholm", options: ["Stockholm", "Göteborg", "Malmö", "Uppsala"] },
    { q: "ABBA er forkortet efter medlemmernes fornavne. Hvilke fire?", a: "Agnetha, Björn, Benny, Anni-Frid", options: ["Agnetha, Björn, Benny, Anni-Frid", "Agnes, Bo, Bertil, Anita", "Anna, Bjarne, Birger, Astrid", "Anders, Björn, Bodil, Anni-Frid"] },
    { q: "Hvilken sang har lyrikken 'You can dance, you can jive, having the time of your life'?", a: "Dancing Queen", options: ["Dancing Queen", "Mamma Mia", "Voulez-Vous", "Super Trouper"] },
    { q: "Hvilken sang har lyrikken 'My my, at Waterloo Napoleon did surrender'?", a: "Waterloo", options: ["Waterloo", "Fernando", "SOS", "Gimme! Gimme! Gimme!"] },
    { q: "Hvilken ABBA-sang fra 1980 handler om en bittersød skilsmisse?", a: "The Winner Takes It All", options: ["The Winner Takes It All", "SOS", "Knowing Me, Knowing You", "Money, Money, Money"] },
    { q: "Hvilken sang åbner med 'I've been cheated by you since I don't know when'?", a: "Mamma Mia", options: ["Mamma Mia", "Dancing Queen", "Take a Chance on Me", "SOS"] },
    { q: "Hvilken sang åbner med 'I have a dream, a song to sing'?", a: "I Have a Dream", options: ["I Have a Dream", "Thank You for the Music", "Chiquitita", "Eagle"] },
    { q: "Hvilken film fra 2008 er bygget på ABBA-sange?", a: "Mamma Mia!", options: ["Mamma Mia!", "Across the Universe", "Yesterday", "Jersey Boys"] },
    { q: "Hvem spiller hovedrollen Donna i Mamma Mia! (2008)?", a: "Meryl Streep", options: ["Meryl Streep", "Susan Sarandon", "Glenn Close", "Sigourney Weaver"] },
    { q: "Hvilket år havde 'Mamma Mia! Here We Go Again' premiere?", a: "2018", options: ["2014", "2016", "2018", "2020"] },
    { q: "Hvilket album fra 2021 markerede ABBA's comeback efter 40 år?", a: "Voyage", options: ["Voyage", "The Visitors", "Super Trouper II", "Reunion"] },
    { q: "Hvor blev 'ABBA Voyage'-koncerten åbnet i 2022?", a: "London", options: ["London", "Stockholm", "New York", "Las Vegas"] },
    { q: "Hvad var særligt ved ABBA Voyage-koncerten i 2022?", a: "Bandet optrådte som digitale avatarer", options: ["Bandet optrådte som digitale avatarer", "Det var deres første live-show siden 1979", "Bandet spillede uden publikum til stede", "Koncerten varede over otte timer"] },
    { q: "ABBA bestod af to par. Hvilket?", a: "Agnetha+Björn og Anni-Frid+Benny", options: ["Agnetha+Björn og Anni-Frid+Benny", "Agnetha+Benny og Anni-Frid+Björn", "Agnetha+Anni-Frid og Björn+Benny", "Astrid+Bjarne og Anita+Bo"] },
    { q: "Hvilket år gik ABBA officielt på pause?", a: "1982", options: ["1980", "1981", "1982", "1983"] },
    { q: "Hvilken sang fra 1976 har lyrikken 'Money money money, must be funny'?", a: "Money, Money, Money", options: ["Money, Money, Money", "Take a Chance on Me", "Voulez-Vous", "Super Trouper"] },
    { q: "Hvilken ABBA-sang blev #1 i USA?", a: "Dancing Queen", options: ["Dancing Queen", "Waterloo", "Mamma Mia", "SOS"] },
    { q: "I hvilket land blev Eurovision afholdt da ABBA vandt i 1974?", a: "Storbritannien", options: ["Storbritannien", "Sverige", "Frankrig", "Holland"] },
    { q: "Hvor mange studiealbum udgav ABBA mellem 1973 og 1981?", a: "8", options: ["6", "7", "8", "9"] },
    { q: "Hvilken ABBA-sang citerer linjen 'Super Trouper beams are gonna blind me'?", a: "Super Trouper", options: ["Super Trouper", "Voulez-Vous", "Eagle", "Knowing Me, Knowing You"] },
    { q: "Hvilken sang åbner med 'Chiquitita, tell me what's wrong'?", a: "Chiquitita", options: ["Chiquitita", "Fernando", "Andante, Andante", "SOS"] },
    { q: "Hvilken disco-præget sang fra 1979 betyder 'vil du?' på fransk?", a: "Voulez-Vous", options: ["Voulez-Vous", "Mamma Mia", "Knowing Me, Knowing You", "Money, Money, Money"] },
    { q: "Hvilken ballade fra 1976 handler om en mexicansk frihedskæmper?", a: "Fernando", options: ["Fernando", "Chiquitita", "Andante, Andante", "El Niño"] },
    { q: "Hvilken sang åbner Mamma Mia!-filmen (2008)?", a: "I Have a Dream", options: ["I Have a Dream", "Mamma Mia", "Honey, Honey", "Money, Money, Money"] },
    { q: "Hvor mange plader har ABBA solgt globalt (cirka)?", a: "Ca. 380 millioner", options: ["Ca. 380 millioner", "Ca. 100 millioner", "Ca. 200 millioner", "Ca. 600 millioner"] },
    { q: "Hvem var den blonde sangerinde i ABBA?", a: "Agnetha Fältskog", options: ["Agnetha Fältskog", "Anni-Frid Lyngstad", "Lill-Babs Svensson", "Carola Häggkvist"] }
  ],
  "Børnesange": [
    { q: "Hvilken børnesang handler om en lille bille der har mistet sin mor?", a: "Mariehøne Evigglad", options: ["Mariehøne Evigglad", "Bjørnen Sover", "Lille Peter Edderkop", "Solen Er Så Rød"] },
    { q: "I 'Lille Peter Edderkop' — hvor kravler edderkoppen op?", a: "Op ad muren", options: ["Op ad muren", "Op ad et træ", "Op ad stigen", "Ud af brønden"] },
    { q: "Hvilken børnesang er den danske version af franske 'Frère Jacques'?", a: "Mester Jakob", options: ["Mester Jakob", "Sov nu lille Lasse", "Bjørnen Sover", "Tornerose"] },
    { q: "Hvilken sang er den danske version af 'Old MacDonald Had a Farm'?", a: "Jens Hansen havde en bondegård", options: ["Jens Hansen havde en bondegård", "Hans og hans hane", "Mads i marken", "Per og Pollyanna"] },
    { q: "Hvem skrev børnerim som 'Den lille frække Frederik' og 'Noget om helte'?", a: "Halfdan Rasmussen", options: ["Halfdan Rasmussen", "Benny Andersen", "Piet Hein", "Tove Ditlevsen"] },
    { q: "Hvem er værten i tv-programmet 'Sigurd og symfoniorkesteret'?", a: "Sigurd Barrett", options: ["Sigurd Barrett", "Sebastian Klein", "Onkel Reje", "Hr. Skæg"] },
    { q: "I 'Bjørnen sover' — hvad advarer sangen om?", a: "At man aldrig kan stole på bjørnen", options: ["At man aldrig kan stole på bjørnen", "At bjørnen er sulten", "At bjørnen har fået unger", "At bjørnen er blevet konge"] },
    { q: "Hvilken dansk komponist skrev musikken til 'Solen er så rød, mor'?", a: "Carl Nielsen", options: ["Carl Nielsen", "Niels W. Gade", "Otto Mortensen", "Thomas Laub"] },
    { q: "Hvad gør ulven i 'Tre små grise'?", a: "Puster husene omkuld", options: ["Puster husene omkuld", "Sætter ild til skoven", "Stjæler grisenes mad", "Sender breve til grisene"] },
    { q: "Hvilken dansk musiker har sat melodi til mange af Halfdan Rasmussens digte?", a: "Sebastian", options: ["Sebastian", "Kim Larsen", "Anne Linnet", "Lars H.U.G."] },
    { q: "Hvad hedder Pippi Langstrømpes abe?", a: "Hr. Nilsson", options: ["Hr. Nilsson", "Hr. Andersson", "Hr. Skogsberg", "Hr. Pettersson"] },
    { q: "Hvilket land kommer historierne om Pippi Langstrømpe fra?", a: "Sverige", options: ["Sverige", "Norge", "Danmark", "Finland"] },
    { q: "Hvem skrev bøgerne om Pippi Langstrømpe?", a: "Astrid Lindgren", options: ["Astrid Lindgren", "Tove Jansson", "Selma Lagerlöf", "Maria Gripe"] },
    { q: "Hvilken farve har Pippi Langstrømpes hår?", a: "Rødt", options: ["Rødt", "Blondt", "Sort", "Brunt"] },
    { q: "Hvad hedder DR's tv-kanal for de mindste børn?", a: "DR Ramasjang", options: ["DR Ramasjang", "DR Ultra", "DR Børn", "DR Junior"] },
    { q: "I sangen 'Hjulene på bussen' — hvad gør hjulene?", a: "De drejer rundt", options: ["De drejer rundt", "De hopper op og ned", "De synger en sang", "De vinker farvel"] },
    { q: "Hvor bor Pippi Langstrømpe?", a: "Villa Villekulla", options: ["Villa Villekulla", "Skraldely", "Stjernevillaen", "Solgården"] },
    { q: "Hvad hedder Pippis bedste venner?", a: "Tommy og Annika", options: ["Tommy og Annika", "Emil og Ida", "Bo og Kalle", "Madicken og Lisabet"] },
    { q: "Hvilken dansk forfatter skrev eventyrene 'Klods-Hans' og 'Den Grimme Ælling'?", a: "H.C. Andersen", options: ["H.C. Andersen", "Brødrene Grimm", "Astrid Lindgren", "Halfdan Rasmussen"] },
    { q: "I H.C. Andersens 'Den Grimme Ælling' — hvad bliver ællingen til?", a: "En svane", options: ["En svane", "En and", "En gås", "En ørn"] },
    { q: "Hvilken H.C. Andersen-historie inspirerede Disney-filmen 'Frost'?", a: "Snedronningen", options: ["Snedronningen", "Den Lille Havfrue", "Tommelise", "Klods-Hans"] },
    { q: "I 'Kejserens Nye Klæder' — hvordan er kejserens nye tøj?", a: "Det eksisterer ikke", options: ["Det eksisterer ikke", "Det er lavet af guld", "Det er for lille", "Det er spundet af edderkoppespind"] },
    { q: "Hvilken børnesang handler om en krage på en gren der bliver skudt af en jæger?", a: "Højt på en gren en krage sad", options: ["Højt på en gren en krage sad", "Bjørnen sover", "Lille kat lille kat", "Mariehøne Evigglad"] },
    { q: "Hvilken dansk musiker skrev musikken til musicalen 'Skatteøen' fra 1989?", a: "Sebastian", options: ["Sebastian", "Kim Larsen", "Lars H.U.G.", "Sanne Salomonsen"] },
    { q: "Hvad hedder kaptajn Langstrømpes skib (Pippi's far)?", a: "Hoppetosse", options: ["Hoppetosse", "Stjernepige", "Sjøfugl", "Villekulla"] },
    { q: "Hvilken finsk forfatter skabte Mumitrolde-universet?", a: "Tove Jansson", options: ["Tove Jansson", "Astrid Lindgren", "Selma Lagerlöf", "Maria Parr"] },
    { q: "Hvilken dansk forfatter skrev billedbogen 'Cykelmyggen Egon'?", a: "Flemming Quist Møller", options: ["Flemming Quist Møller", "Halfdan Rasmussen", "Benny Andersen", "Bent Haller"] },
    { q: "Hvilken nordmand skrev 'Folk og røvere i Kardemomme By'?", a: "Thorbjørn Egner", options: ["Thorbjørn Egner", "Jostein Gaarder", "Henrik Ibsen", "Jo Nesbø"] },
    { q: "Hvilket dansk band står bag børnesangen 'Bamses Billedbog'?", a: "Bamses Venner", options: ["Bamses Venner", "Shu-bi-dua", "Sebastian", "TV-2"] },
    { q: "Hvilken figur fra Ramasjang er kendt for at sige 'Hokus Pokus Filiokus'?", a: "Hr. Skæg", options: ["Hr. Skæg", "Onkel Reje", "Sebastian Klein", "Sigurd Barrett"] }
  ],
  "Disney": [
    { q: "Sangen 'Let It Go' er fra hvilken Disney-film?", a: "Frost", options: ["Frost", "Vaiana", "Aladdin", "Den Lille Havfrue"] },
    { q: "I hvilken Disney-film synges 'Hakuna Matata'?", a: "Løvernes Konge", options: ["Løvernes Konge", "Junglebogen", "Madagascar", "Bambi"] },
    { q: "Sangen 'A Whole New World' er fra:", a: "Aladdin", options: ["Aladdin", "Cinderella", "Pocahontas", "Mulan"] },
    { q: "I hvilken Disney-film synges 'Be Our Guest' af stagende kandelabre og urværk?", a: "Skønheden og Udyret", options: ["Skønheden og Udyret", "Cinderella", "Snehvide", "Tornerose"] },
    { q: "Sangen 'Under the Sea' synges af krabben Sebastian i:", a: "Den Lille Havfrue", options: ["Den Lille Havfrue", "Find Nemo", "Vaiana", "Pocahontas"] },
    { q: "Sangen 'Circle of Life' åbner hvilken Disney-film?", a: "Løvernes Konge", options: ["Løvernes Konge", "Tarzan", "Bambi", "Brother Bear"] },
    { q: "Hvem synger 'When You Wish Upon a Star' i den originale 'Pinocchio'?", a: "Jiminy Cricket", options: ["Jiminy Cricket", "Geppetto", "Pinocchio", "Den Blå Fe"] },
    { q: "Hvor mange dværge er der i 'Snehvide og de syv små dværge'?", a: "Syv", options: ["Syv", "Seks", "Otte", "Fem"] },
    { q: "Sangen 'Bare Necessities' synges af bjørnen Baloo i hvilken film?", a: "Junglebogen", options: ["Junglebogen", "Robin Hood", "Brother Bear", "Bambi"] },
    { q: "Sangene 'How Far I'll Go' og 'You're Welcome' er fra hvilken Disney-film?", a: "Vaiana", options: ["Vaiana", "Frost", "Pocahontas", "Den Lille Havfrue"] },
    { q: "I hvilken Disney-film synges 'We Don't Talk About Bruno'?", a: "Encanto", options: ["Encanto", "Coco", "Vaiana", "Frost 2"] },
    { q: "Sangen 'Reflection' synges af titelfiguren i:", a: "Mulan", options: ["Mulan", "Pocahontas", "Vaiana", "Snehvide"] },
    { q: "Hvilken figur synger 'Friend Like Me' i 'Aladdin'?", a: "Ånden", options: ["Ånden", "Aladdin", "Jasmin", "Sultanen"] },
    { q: "Hvad hedder den røde krabbe der synger 'Under the Sea' i 'Den Lille Havfrue'?", a: "Sebastian", options: ["Sebastian", "Sebastien", "Crabbe", "Coral"] },
    { q: "Hvad hedder havfruen i 'Den Lille Havfrue'?", a: "Ariel", options: ["Ariel", "Belle", "Pocahontas", "Tiana"] },
    { q: "Hvad hedder prinsessen i 'Skønheden og Udyret'?", a: "Belle", options: ["Belle", "Cinderella", "Aurora", "Ariel"] },
    { q: "Hvilken Disney-prinsesse forklæder sig som mand for at gå i krig for sin far?", a: "Mulan", options: ["Mulan", "Pocahontas", "Vaiana", "Merida"] },
    { q: "Sangen 'Colors of the Wind' synges af:", a: "Pocahontas", options: ["Pocahontas", "Mulan", "Vaiana", "Belle"] },
    { q: "'I See the Light' synges af Rapunzel og Flynn i:", a: "To på flugt", options: ["To på flugt", "Frost", "Cinderella", "Tornerose"] },
    { q: "Sangen 'Try Everything' åbner hvilken animationsfilm fra Disney?", a: "Zootropolis", options: ["Zootropolis", "Big Hero 6", "Vaiana", "Ralph Bryder Internettet"] },
    { q: "Sangen 'Remember Me' er fra hvilken Pixar-film om de dødes dag?", a: "Coco", options: ["Coco", "Onward", "Sjæl", "Up"] },
    { q: "Mary Poppins synger 'Spoonful of Sugar'. Hvad er hendes job i familien Banks?", a: "Barnepige", options: ["Barnepige", "Lærer", "Tjener", "Sygeplejerske"] },
    { q: "'Bibbidi-Bobbidi-Boo' er en magisk besværgelse fra hvilken Disney-film?", a: "Cinderella", options: ["Cinderella", "Snehvide", "Tornerose", "Den Lille Havfrue"] },
    { q: "Hvilken Disney-prinsesse vågner med et kys efter at have spist et forgiftet æble?", a: "Snehvide", options: ["Snehvide", "Tornerose", "Cinderella", "Belle"] },
    { q: "Sangene 'Into the Unknown' og 'Show Yourself' er fra:", a: "Frost 2", options: ["Frost 2", "Vaiana 2", "Tornerose", "Den Lille Havfrue 2"] },
    { q: "I hvilken Disney-film synges 'I'll Make a Man Out of You'?", a: "Mulan", options: ["Mulan", "Hercules", "Pocahontas", "Tarzan"] },
    { q: "Tiana fra 'Prinsessen og Frøen' drømmer om at åbne sin egen:", a: "Restaurant", options: ["Restaurant", "Frisørsalon", "Boghandel", "Modebutik"] },
    { q: "Sangene 'Touch the Sky' og 'Into the Open Air' er fra hvilken Pixar-film med en skotsk prinsesse?", a: "Modig", options: ["Modig", "Frost", "Vaiana", "Den Utrolige Familie"] },
    { q: "Hvilken klassisk Disney-figur er en flyvende cirkus-elefant?", a: "Dumbo", options: ["Dumbo", "Bambi", "Tarzan", "Pinocchio"] },
    { q: "Titelsangen 'Beauty and the Beast' synges af tekanden Mrs. Potts. Hvor finder filmen sted?", a: "På et fortryllet slot i Frankrig", options: ["På et fortryllet slot i Frankrig", "I et engelsk landsby", "I et tysk skovkloster", "På en italiensk øde ø"] }
  ],
  "Lyt og Gæt": [
    { q: "Hvilket band spiller?", a: "a-ha", options: ["a-ha", "Duran Duran", "Depeche Mode", "Pet Shop Boys"], spotify: "https://open.spotify.com/track/2WfaOiMkCvy7F5fcp2zZ8L" },
    { q: "Hvilken kunstner spiller?", a: "Michael Jackson", options: ["Michael Jackson", "Prince", "Stevie Wonder", "Lionel Richie"], spotify: "https://open.spotify.com/track/5ChkMS8OtdzJeqyybCc9R5" },
    { q: "Hvilket band spiller?", a: "Guns N' Roses", options: ["Guns N' Roses", "Bon Jovi", "Mötley Crüe", "Def Leppard"], spotify: "https://open.spotify.com/track/7o2CTH4ctstm8TNelqjb51" },
    { q: "Hvilket band spiller?", a: "Journey", options: ["Journey", "Foreigner", "REO Speedwagon", "Styx"], spotify: "https://open.spotify.com/track/4bHsxqR3GMrXTxEPLuK5ue" },
    { q: "Hvilket band spiller?", a: "Toto", options: ["Toto", "Genesis", "Foreigner", "Asia"], spotify: "https://open.spotify.com/track/0PX5DeeFUEVhA5LEeomIlG" },
    { q: "Hvilket band spiller?", a: "Nirvana", options: ["Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains"], spotify: "https://open.spotify.com/track/5JMfIuCTLE8p6mujmZGKB9" },
    { q: "Hvilket band spiller?", a: "Oasis", options: ["Oasis", "Blur", "Radiohead", "The Verve"], spotify: "https://open.spotify.com/track/5wj4E6IsrVtn8IBJQOd0Cl" },
    { q: "Hvilket band spiller?", a: "Led Zeppelin", options: ["Led Zeppelin", "Deep Purple", "Black Sabbath", "Pink Floyd"], spotify: "https://open.spotify.com/track/5CQ30WqJwcep0pYcV4AMNc" },
    { q: "Hvilket band spiller?", a: "Queen", options: ["Queen", "The Rolling Stones", "The Who", "The Kinks"], spotify: "https://open.spotify.com/track/7tFiyTwD0nx5a1eklYtX2J" },
    { q: "Hvilket band spiller?", a: "Eagles", options: ["Eagles", "Fleetwood Mac", "The Doors", "Creedence Clearwater Revival"], spotify: "https://open.spotify.com/track/40riOy7x9W7GXjyGp4pjAv" },
    { q: "Hvilket band spiller?", a: "Deep Purple", options: ["Deep Purple", "Led Zeppelin", "Black Sabbath", "Uriah Heep"], spotify: "https://open.spotify.com/track/5SAUIWdZ04OxYfJFDchC7S" },
    { q: "Hvilken dansk kunstner spiller?", a: "Kim Larsen", options: ["Kim Larsen", "Sebastian", "Thomas Helmig", "Lars H.U.G."], spotify: "https://open.spotify.com/track/6FvyN8jVNDNsOREm5VDlex" },
    { q: "Hvilket dansk band spiller?", a: "Gasolin'", options: ["Gasolin'", "Sort Sol", "TV-2", "Gnags"], spotify: "https://open.spotify.com/track/4Z4kEP9at1yOoAPtaBLp4P" },
    { q: "Hvilket dansk-norsk band spiller?", a: "Aqua", options: ["Aqua", "Toy-Box", "Ace of Base", "Vengaboys"], spotify: "https://open.spotify.com/track/6SIDRn0OX4I8sGsDa4eCOZ" },
    { q: "Hvilken kunstner spiller?", a: "Madonna", options: ["Madonna", "Cyndi Lauper", "Whitney Houston", "Janet Jackson"], spotify: "https://open.spotify.com/track/1ZPlNanZsJSPK5h9YZZFbZ" },
    { q: "Hvilket band spiller?", a: "The Police", options: ["The Police", "U2", "Dire Straits", "The Cure"], spotify: "https://open.spotify.com/track/1JSTJqkT5qHq8MDJnJbRE1" },
    { q: "Hvilken kunstner spiller?", a: "Prince", options: ["Prince", "Michael Jackson", "George Michael", "David Bowie"], spotify: "https://open.spotify.com/track/54X78diSLoUDI3joC2bjMz" },
    { q: "Hvilken kunstner spiller?", a: "Cyndi Lauper", options: ["Cyndi Lauper", "Madonna", "Pat Benatar", "Blondie"], spotify: "https://open.spotify.com/track/4y1LsJpmMti1PfRQV9AWWe" },
    { q: "Hvilket band spiller?", a: "Europe", options: ["Europe", "Whitesnake", "Scorpions", "Survivor"], spotify: "https://open.spotify.com/track/3MrRksHupTVEQ7YbA0FsZK" },
    { q: "Hvilket band spiller?", a: "Wham!", options: ["Wham!", "Duran Duran", "Culture Club", "Frankie Goes to Hollywood"], spotify: "https://open.spotify.com/track/0ikz6tENMONtK6qGkOrU3c" }
  ]
};
