const QUESTIONS = {
  "80'er Hits": [
    { q: "Hvilket band sang 'Take On Me' i 1985?", a: "a-ha", options: ["a-ha", "Duran Duran", "Depeche Mode", "Pet Shop Boys"], spotify: "https://open.spotify.com/track/2WfaOiMkCvy7F5fcp2zZ8L" },
    { q: "Hvem sang 'Billie Jean'?", a: "Michael Jackson", options: ["Prince", "Michael Jackson", "Stevie Wonder", "Lionel Richie"], spotify: "https://open.spotify.com/track/5ChkMS8OtdzJeqyybCc9R5" },
    { q: "Hvilket band stod bag 'Sweet Child O' Mine'?", a: "Guns N' Roses", options: ["Guns N' Roses", "Bon Jovi", "Mötley Crüe", "Def Leppard"], spotify: "https://open.spotify.com/track/7o2CTH4ctstm8TNelqjb51" },
    { q: "Hvem sang 'Like a Virgin' i 1984?", a: "Madonna", options: ["Cyndi Lauper", "Madonna", "Whitney Houston", "Janet Jackson"], spotify: "https://open.spotify.com/track/1ZPlNanZsJSPK5h9YZZFbZ" },
    { q: "Hvilket band sang 'Every Breath You Take'?", a: "The Police", options: ["U2", "The Police", "Dire Straits", "The Cure"], spotify: "https://open.spotify.com/track/1JSTJqkT5qHq8MDJnJbRE1" },
    { q: "Hvem sang 'Purple Rain'?", a: "Prince", options: ["Michael Jackson", "Prince", "David Bowie", "George Michael"], spotify: "https://open.spotify.com/track/54X78diSLoUDI3joC2bjMz" },
    { q: "Hvilket band sang 'Don't Stop Believin''?", a: "Journey", options: ["Journey", "Foreigner", "REO Speedwagon", "Styx"], spotify: "https://open.spotify.com/track/4bHsxqR3GMrXTxEPLuK5ue" },
    { q: "Hvem sang 'Girls Just Want to Have Fun'?", a: "Cyndi Lauper", options: ["Madonna", "Cyndi Lauper", "Blondie", "Pat Benatar"], spotify: "https://open.spotify.com/track/4y1LsJpmMti1PfRQV9AWWe" },
    { q: "Hvilket band stod bag 'The Final Countdown'?", a: "Europe", options: ["Europe", "Whitesnake", "Scorpions", "Accept"], spotify: "https://open.spotify.com/track/3MrRksHupTVEQ7YbA0FsZK" },
    { q: "Hvem sang 'I Wanna Dance with Somebody'?", a: "Whitney Houston", options: ["Whitney Houston", "Janet Jackson", "Diana Ross", "Tina Turner"], spotify: "https://open.spotify.com/track/2tUBqZG2AbRi7Q0BIrVrEj" },
    { q: "Hvilket band sang 'Livin' on a Prayer'?", a: "Bon Jovi", options: ["Def Leppard", "Bon Jovi", "Whitesnake", "Poison"], spotify: "https://open.spotify.com/track/37ZJ0p5Jm13JPevGcx4SkF" },
    { q: "Hvem sang 'West End Girls'?", a: "Pet Shop Boys", options: ["Erasure", "Pet Shop Boys", "Soft Cell", "Depeche Mode"], spotify: "https://open.spotify.com/track/5Dqik1P9toCJTLj5rEm78s" },
    { q: "Hvilket band sang 'Enjoy the Silence'?", a: "Depeche Mode", options: ["New Order", "Depeche Mode", "The Cure", "Tears for Fears"], spotify: "https://open.spotify.com/track/6WK9dVrRABMkUXFLNlgWFh" },
    { q: "Hvem sang 'Karma Chameleon'?", a: "Culture Club", options: ["Duran Duran", "Spandau Ballet", "Culture Club", "Wham!"], spotify: "https://open.spotify.com/track/48O0GrGJWml3DzHhC5sJ7a" },
    { q: "Hvilket band sang 'Money for Nothing'?", a: "Dire Straits", options: ["Dire Straits", "Pink Floyd", "ZZ Top", "The Eagles"], spotify: "https://open.spotify.com/track/4yqtwO7MQIIXqoiRBPHAgR" },
    { q: "Hvem sang 'Wake Me Up Before You Go-Go'?", a: "Wham!", options: ["Duran Duran", "Culture Club", "Wham!", "Frankie Goes to Hollywood"], spotify: "https://open.spotify.com/track/0ikz6tENMONtK6qGkOrU3c" },
    { q: "Hvilket band sang 'With or Without You'?", a: "U2", options: ["U2", "Simple Minds", "INXS", "The Cure"], spotify: "https://open.spotify.com/track/6ADSaE87h8Y3lccZlBJdXH" },
    { q: "Hvem sang 'Tainted Love'?", a: "Soft Cell", options: ["Depeche Mode", "Soft Cell", "Pet Shop Boys", "Erasure"], spotify: "https://open.spotify.com/track/58E1XVmZTODC67YNjneuXM" },
    { q: "Hvilket band sang 'Shout'?", a: "Tears for Fears", options: ["Simple Minds", "Tears for Fears", "Duran Duran", "Spandau Ballet"], spotify: "https://open.spotify.com/track/6DSZSiZb8garOqvJ2uRC0E" },
    { q: "Hvem sang 'Relax'?", a: "Frankie Goes to Hollywood", options: ["Wham!", "Frankie Goes to Hollywood", "Pet Shop Boys", "Erasure"], spotify: "https://open.spotify.com/track/1GRtUgilF2IhZusw1sQYx6" },
    { q: "Hvilket band sang 'Blue Monday'?", a: "New Order", options: ["Depeche Mode", "New Order", "Joy Division", "The Smiths"], spotify: "https://open.spotify.com/track/6hHc7Pks7wtBIW8Z6A0iFq" },
    { q: "Hvem sang 'Addicted to Love'?", a: "Robert Palmer", options: ["Bryan Adams", "Robert Palmer", "Phil Collins", "Rick Springfield"], spotify: "https://open.spotify.com/track/5RKO2DLADKAgXfwxxKWIF6" },
    { q: "Hvilket band sang 'Jump'?", a: "Van Halen", options: ["Van Halen", "Def Leppard", "AC/DC", "Scorpions"], spotify: "https://open.spotify.com/track/7N3PAbqfTjSEU1edb2tY8j" },
    { q: "Hvem sang 'Private Eyes'?", a: "Hall & Oates", options: ["The Police", "Hall & Oates", "Duran Duran", "Tears for Fears"], spotify: "https://open.spotify.com/track/5HQ639Z3ms3hnZx0KfWnkp" },
    { q: "Hvilket band sang 'Under Pressure'?", a: "Queen & David Bowie", options: ["Queen & David Bowie", "Dire Straits", "Genesis", "The Police"], spotify: "https://open.spotify.com/track/2fuCquhmrzHpu5xcA1ci9x" },
    { q: "Hvem sang 'Never Gonna Give You Up'?", a: "Rick Astley", options: ["George Michael", "Rick Astley", "Billy Ocean", "Bobby Brown"], spotify: "https://open.spotify.com/track/1GokOKpjcb4Vg0kPfZMTyn" },
    { q: "Hvilket band sang 'Hunger Strike'?", a: "Temple of the Dog", options: ["Pearl Jam", "Temple of the Dog", "Soundgarden", "Alice in Chains"], spotify: "https://open.spotify.com/track/0W7AbEauB7cP4pidLclApe" },
    { q: "Hvem sang 'Faith'?", a: "George Michael", options: ["George Michael", "Rick Astley", "Phil Collins", "Sting"], spotify: "https://open.spotify.com/track/1eKhntRLUPDV7h6tATtzsv" },
    { q: "Hvilket band sang 'Pour Some Sugar on Me'?", a: "Def Leppard", options: ["Def Leppard", "Poison", "Mötley Crüe", "Bon Jovi"], spotify: "https://open.spotify.com/track/1aZLIbKEdsyqxyD6iNcrbA" },
    { q: "Hvem sang 'Africa'?", a: "Toto", options: ["Toto", "Genesis", "Phil Collins", "Foreigner"], spotify: "https://open.spotify.com/track/0PX5DeeFUEVhA5LEeomIlG" },
    { q: "Hvilket band sang 'Need You Tonight'?", a: "INXS", options: ["INXS", "Duran Duran", "Simple Minds", "U2"], spotify: "https://open.spotify.com/track/5eU8qMd0TpaLqTGDZJaLDs" }
  ],
  "90'er Hits": [
    { q: "Hvilket band sang 'Smells Like Teen Spirit'?", a: "Nirvana", options: ["Nirvana", "Pearl Jam", "Soundgarden", "Alice in Chains"], spotify: "https://open.spotify.com/track/5JMfIuCTLE8p6mujmZGKB9" },
    { q: "Hvem sang 'Wannabe' i 1996?", a: "Spice Girls", options: ["Spice Girls", "All Saints", "Destiny's Child", "TLC"], spotify: "https://open.spotify.com/track/1Je1IMUlBXcx1Fz0WE7oPT" },
    { q: "Hvilket band sang 'Creep'?", a: "Radiohead", options: ["Radiohead", "Oasis", "Blur", "Pulp"], spotify: "https://open.spotify.com/track/70LcF31zb1H0PyJoS1Sx1r" },
    { q: "Hvem sang 'I Will Always Love You' (filmversion)?", a: "Whitney Houston", options: ["Mariah Carey", "Whitney Houston", "Celine Dion", "Dolly Parton"], spotify: "https://open.spotify.com/track/4eHbdreAnSOrDDsFfc4Fpm" },
    { q: "Hvilket band sang 'Wonderwall'?", a: "Oasis", options: ["Blur", "Oasis", "Radiohead", "The Verve"], spotify: "https://open.spotify.com/track/5wj4E6IsrVtn8IBJQOd0Cl" },
    { q: "Hvem sang 'No Diggity'?", a: "Blackstreet", options: ["Blackstreet", "Boyz II Men", "TLC", "SWV"], spotify: "https://open.spotify.com/track/6MdqqkQ8sSC0WB4i8PyRuQ" },
    { q: "Hvilket band sang 'Losing My Religion'?", a: "R.E.M.", options: ["R.E.M.", "U2", "Pearl Jam", "The Cranberries"], spotify: "https://open.spotify.com/track/31AOj9sFz2gM0O3hMARRBx" },
    { q: "Hvem sang 'Baby One More Time'?", a: "Britney Spears", options: ["Christina Aguilera", "Britney Spears", "Mandy Moore", "Jessica Simpson"], spotify: "https://open.spotify.com/track/3MjUtNVVq3C8Fn0MP3zhXa" },
    { q: "Hvilket band sang 'Bitter Sweet Symphony'?", a: "The Verve", options: ["Oasis", "The Verve", "Blur", "Radiohead"], spotify: "https://open.spotify.com/track/5yEPxDjbbzUzyauGtnmVEC" },
    { q: "Hvem sang 'Waterfalls'?", a: "TLC", options: ["Destiny's Child", "TLC", "En Vogue", "SWV"], spotify: "https://open.spotify.com/track/6qspW4YKycviDFjHBOaqUY" },
    { q: "Hvilket band sang 'Under the Bridge'?", a: "Red Hot Chili Peppers", options: ["Pearl Jam", "Red Hot Chili Peppers", "Nirvana", "Soundgarden"], spotify: "https://open.spotify.com/track/3d9DChrdc6BOeFsbrZ3Is0" },
    { q: "Hvem sang 'My Heart Will Go On'?", a: "Celine Dion", options: ["Whitney Houston", "Celine Dion", "Mariah Carey", "Barbra Streisand"], spotify: "https://open.spotify.com/track/33LC84JgLvK2KuW43MfaNq" },
    { q: "Hvilket band sang 'Song 2'?", a: "Blur", options: ["Oasis", "Blur", "Pulp", "Suede"], spotify: "https://open.spotify.com/track/1FTSo4v6BOZH9QxKc3MbVM" },
    { q: "Hvem sang 'Gangsta's Paradise'?", a: "Coolio", options: ["Coolio", "2Pac", "Notorious B.I.G.", "Snoop Dogg"], spotify: "https://open.spotify.com/track/1DIXPcTDzTj8ZMHt3PDt8p" },
    { q: "Hvilket band sang 'Zombie'?", a: "The Cranberries", options: ["The Cranberries", "Garbage", "No Doubt", "Hole"], spotify: "https://open.spotify.com/track/2IZZqH4K02UIYg5EohpNHF" },
    { q: "Hvem sang 'MMMBop'?", a: "Hanson", options: ["Backstreet Boys", "Hanson", "*NSYNC", "98 Degrees"], spotify: "https://open.spotify.com/track/0lnxrQAd9ZxbhBBe7d8FO8" },
    { q: "Hvilket band sang 'Everybody (Backstreet's Back)'?", a: "Backstreet Boys", options: ["Backstreet Boys", "*NSYNC", "Westlife", "98 Degrees"], spotify: "https://open.spotify.com/track/1XgpkuprL618Ps5OCrNKsX" },
    { q: "Hvem sang 'Livin' La Vida Loca'?", a: "Ricky Martin", options: ["Enrique Iglesias", "Ricky Martin", "Marc Anthony", "Julio Iglesias"], spotify: "https://open.spotify.com/track/0Ph6L4l8dYUuXFmb71Ajnd" },
    { q: "Hvilket band sang 'Enter Sandman'?", a: "Metallica", options: ["Metallica", "Megadeth", "Slayer", "Pantera"], spotify: "https://open.spotify.com/track/3VqHuw0wFlIHcIPWkhIbdQ" },
    { q: "Hvem sang 'I Believe I Can Fly'?", a: "R. Kelly", options: ["R. Kelly", "Seal", "Boyz II Men", "Brian McKnight"], spotify: "https://open.spotify.com/track/2RzJwBCXsS1VnjDm2jKKAa" },
    { q: "Hvilket band sang 'Common People'?", a: "Pulp", options: ["Oasis", "Blur", "Pulp", "The Verve"], spotify: "https://open.spotify.com/track/2fXKyAyPrEa24c6PJyqznF" },
    { q: "Hvem sang 'Torn'?", a: "Natalie Imbruglia", options: ["Natalie Imbruglia", "Alanis Morissette", "Sheryl Crow", "Jewel"], spotify: "https://open.spotify.com/track/1Jaah2tmN9Hv81A87KZ1MU" },
    { q: "Hvilket band sang 'No Rain'?", a: "Blind Melon", options: ["Blind Melon", "Stone Temple Pilots", "Bush", "Live"], spotify: "https://open.spotify.com/track/21DWWIIOUrDI1pOditm6uR" },
    { q: "Hvem sang 'Ironic'?", a: "Alanis Morissette", options: ["Alanis Morissette", "Sheryl Crow", "Fiona Apple", "Tori Amos"], spotify: "https://open.spotify.com/track/29YBihzQOmat0U74k4ukdx" },
    { q: "Hvilket band sang 'Black Hole Sun'?", a: "Soundgarden", options: ["Pearl Jam", "Nirvana", "Soundgarden", "Alice in Chains"], spotify: "https://open.spotify.com/track/2EoOZnxNgtmZaD8uUmz2nD" },
    { q: "Hvem sang 'Kiss from a Rose'?", a: "Seal", options: ["Seal", "Sade", "Des'ree", "Terence Trent D'Arby"], spotify: "https://open.spotify.com/track/5CcEC3jMtfB04kr4cBjp6q" },
    { q: "Hvilket band sang 'Killing in the Name'?", a: "Rage Against the Machine", options: ["Rage Against the Machine", "System of a Down", "Korn", "Tool"], spotify: "https://open.spotify.com/track/59WN2psjkt1tyaxjspN8fp" },
    { q: "Hvem sang 'Return of the Mack'?", a: "Mark Morrison", options: ["Craig David", "Mark Morrison", "Shaggy", "Sean Paul"], spotify: "https://open.spotify.com/track/3jDdpx9PMlfMBS5tOBHFm9" },
    { q: "Hvilket band sang 'Basket Case'?", a: "Green Day", options: ["Green Day", "Blink-182", "The Offspring", "Bad Religion"], spotify: "https://open.spotify.com/track/6L89mwZXSOwYl76YXfX13s" },
    { q: "Hvem sang 'You Oughta Know'?", a: "Alanis Morissette", options: ["Alanis Morissette", "Sheryl Crow", "Courtney Love", "PJ Harvey"], spotify: "https://open.spotify.com/track/0Dw9z44gXhplDh5HCWZIxP" },
    { q: "Hvilket band sang 'Tubthumping'?", a: "Chumbawamba", options: ["Chumbawamba", "The Prodigy", "Fatboy Slim", "Underworld"], spotify: "https://open.spotify.com/track/2JLRcAkPB8JZIIohZarVTr" }
  ],
  "Klassisk Rock": [
    { q: "Hvilket band sang 'Stairway to Heaven'?", a: "Led Zeppelin", options: ["Led Zeppelin", "Deep Purple", "Black Sabbath", "Pink Floyd"], spotify: "https://open.spotify.com/track/5CQ30WqJwcep0pYcV4AMNc" },
    { q: "Hvem sang 'Bohemian Rhapsody'?", a: "Queen", options: ["Queen", "The Rolling Stones", "The Beatles", "The Who"], spotify: "https://open.spotify.com/track/7tFiyTwD0nx5a1eklYtX2J" },
    { q: "Hvilket band sang 'Hotel California'?", a: "Eagles", options: ["Eagles", "Fleetwood Mac", "The Doors", "Creedence Clearwater Revival"], spotify: "https://open.spotify.com/track/40riOy7x9W7GXjyGp4pjAv" },
    { q: "Hvem sang 'Satisfaction'?", a: "The Rolling Stones", options: ["The Rolling Stones", "The Beatles", "The Who", "The Kinks"], spotify: "https://open.spotify.com/track/2PzU4IB8Dr6mxV3lHuaG34" },
    { q: "Hvilket band sang 'Comfortably Numb'?", a: "Pink Floyd", options: ["Led Zeppelin", "Pink Floyd", "Yes", "Genesis"], spotify: "https://open.spotify.com/track/5HNCy40Ni5BZJFw1TKzRsC" },
    { q: "Hvem sang 'Born to Run'?", a: "Bruce Springsteen", options: ["Bruce Springsteen", "Bob Seger", "Tom Petty", "John Mellencamp"], spotify: "https://open.spotify.com/track/6hTcuIQa0sxrrByu9wTD7s" },
    { q: "Hvilket band sang 'Smoke on the Water'?", a: "Deep Purple", options: ["Led Zeppelin", "Deep Purple", "Black Sabbath", "Uriah Heep"], spotify: "https://open.spotify.com/track/5SAUIWdZ04OxYfJFDchC7S" },
    { q: "Hvem sang 'Imagine'?", a: "John Lennon", options: ["Paul McCartney", "John Lennon", "George Harrison", "Ringo Starr"], spotify: "https://open.spotify.com/track/7pKfPomDEeI4TPT6EOYjn9" },
    { q: "Hvilket band sang 'Highway to Hell'?", a: "AC/DC", options: ["AC/DC", "Motörhead", "Judas Priest", "Iron Maiden"], spotify: "https://open.spotify.com/track/2zYzyRzz6pRmhPzyfMEC8s" },
    { q: "Hvem sang 'Space Oddity'?", a: "David Bowie", options: ["Elton John", "David Bowie", "Peter Gabriel", "Marc Bolan"], spotify: "https://open.spotify.com/track/72Z17vmmeQKAg8bptWvpVG" },
    { q: "Hvilket band sang 'Wish You Were Here'?", a: "Pink Floyd", options: ["Pink Floyd", "Led Zeppelin", "Genesis", "Yes"], spotify: "https://open.spotify.com/track/1HzDhHApjdjXPLHF6GGYhu" },
    { q: "Hvem sang 'Born in the U.S.A.'?", a: "Bruce Springsteen", options: ["Bruce Springsteen", "John Mellencamp", "Tom Petty", "Bob Seger"], spotify: "https://open.spotify.com/track/0ng9wGwqJwZKqaKvVcnoY9" },
    { q: "Hvilket band sang 'Paranoid'?", a: "Black Sabbath", options: ["Black Sabbath", "Led Zeppelin", "Deep Purple", "Judas Priest"], spotify: "https://open.spotify.com/track/3L8WgDYS5TtwbyxOPSAiFf" },
    { q: "Hvem sang 'Let It Be'?", a: "The Beatles", options: ["The Beatles", "The Rolling Stones", "The Who", "The Kinks"], spotify: "https://open.spotify.com/track/7iN1s7xHE4ifF5povM6A48" },
    { q: "Hvilket band sang 'Free Bird'?", a: "Lynyrd Skynyrd", options: ["Lynyrd Skynyrd", "The Allman Brothers Band", "ZZ Top", "Eagles"], spotify: "https://open.spotify.com/track/5EWPGh7jbTNO2wakv8LjUI" },
    { q: "Hvem sang 'Light My Fire'?", a: "The Doors", options: ["The Doors", "Jimi Hendrix", "The Rolling Stones", "Cream"], spotify: "https://open.spotify.com/track/5uvosCdMlFdTXhoazkTI5R" },
    { q: "Hvilket band sang 'We Will Rock You'?", a: "Queen", options: ["Queen", "Kiss", "AC/DC", "Aerosmith"], spotify: "https://open.spotify.com/track/54flyrjcdnQdco7300avMJ" },
    { q: "Hvem sang 'Layla'?", a: "Derek and the Dominos (Eric Clapton)", options: ["Derek and the Dominos (Eric Clapton)", "Jimi Hendrix", "Jeff Beck", "Peter Green"], spotify: "https://open.spotify.com/track/0S2cMsSo3KgOQF8QdxgYrk" },
    { q: "Hvilket band sang 'Roxanne'?", a: "The Police", options: ["The Clash", "The Police", "The Jam", "Blondie"], spotify: "https://open.spotify.com/track/3EYOJ48Et32uATr9ZmLnAo" },
    { q: "Hvem sang 'Whole Lotta Love'?", a: "Led Zeppelin", options: ["Led Zeppelin", "Deep Purple", "Black Sabbath", "The Who"], spotify: "https://open.spotify.com/track/0hCB0YR03f6AmQaHbwWDe8" },
    { q: "Hvilket band sang 'Won't Get Fooled Again'?", a: "The Who", options: ["The Who", "The Rolling Stones", "The Clash", "The Kinks"], spotify: "https://open.spotify.com/track/0cJPLFrlV7TTCyPLupHzcH" },
    { q: "Hvem sang 'Ziggy Stardust'?", a: "David Bowie", options: ["David Bowie", "T. Rex", "Roxy Music", "Lou Reed"], spotify: "https://open.spotify.com/track/5IyL3XOaRPpTgxVjRIAxXU" },
    { q: "Hvilket band sang 'Dream On'?", a: "Aerosmith", options: ["Aerosmith", "Kiss", "Alice Cooper", "Van Halen"], spotify: "https://open.spotify.com/track/5MxNLUsfh7uzROypsoO5qe" },
    { q: "Hvem sang 'Thunder Road'?", a: "Bruce Springsteen", options: ["Bruce Springsteen", "Bob Seger", "Tom Petty", "Jackson Browne"], spotify: "https://open.spotify.com/track/56lhDZNQ5J47aog6mGKeGk" },
    { q: "Hvilket band sang 'Sultans of Swing'?", a: "Dire Straits", options: ["Dire Straits", "Fleetwood Mac", "Eagles", "The Police"], spotify: "https://open.spotify.com/track/6cr6UDpkjEaMQ80OjWqEBQ" },
    { q: "Hvem sang 'All Along the Watchtower' (mest kendte version)?", a: "Jimi Hendrix", options: ["Bob Dylan", "Jimi Hendrix", "Eric Clapton", "Neil Young"], spotify: "https://open.spotify.com/track/2aoo2jlRnM3A0NyLQqMN2f" },
    { q: "Hvilket band sang 'Paint It Black'?", a: "The Rolling Stones", options: ["The Rolling Stones", "The Beatles", "The Doors", "The Kinks"], spotify: "https://open.spotify.com/track/55hNpOkqiSWoizMJsibifN" },
    { q: "Hvem sang 'Knockin' on Heaven's Door' (original)?", a: "Bob Dylan", options: ["Bob Dylan", "Eric Clapton", "Guns N' Roses", "Neil Young"], spotify: "https://open.spotify.com/track/3WMj8moIAXJhHsyLaqIIHI" },
    { q: "Hvilket band sang 'Sunshine of Your Love'?", a: "Cream", options: ["Cream", "Led Zeppelin", "Jimi Hendrix Experience", "Deep Purple"], spotify: "https://open.spotify.com/track/2K2M0TcglCRLLpFOzKeFZA" },
    { q: "Hvem sang 'Rocket Man'?", a: "Elton John", options: ["David Bowie", "Elton John", "Billy Joel", "Rod Stewart"], spotify: "https://open.spotify.com/track/3gdewACMIVMEWVbyb8O9sY" },
    { q: "Hvilket band sang 'Go Your Own Way'?", a: "Fleetwood Mac", options: ["Fleetwood Mac", "Eagles", "The Doobie Brothers", "Steely Dan"], spotify: "https://open.spotify.com/track/5qg6DB7nxilzxxzalcpNU3" }
  ],
  "Dansk Musik": [
    { q: "Hvem sang 'Midt Om Natten'?", a: "Kim Larsen", options: ["Kim Larsen", "Gasolin'", "TV-2", "Lars H.U.G."], spotify: "https://open.spotify.com/track/6FvyN8jVNDNsOREm5VDlex" },
    { q: "Hvilket dansk band sang 'Kvinde Min'?", a: "Gasolin'", options: ["Gasolin'", "Sort Sol", "TV-2", "Gnags"], spotify: "https://open.spotify.com/track/4Z4kEP9at1yOoAPtaBLp4P" },
    { q: "Hvem sang 'Sommer i Europa'?", a: "Thomas Helmig", options: ["Thomas Helmig", "Kim Larsen", "Rasmus Seebach", "Nik & Jay"], spotify: "https://open.spotify.com/track/3smjXNuVywz0mx8QcdGPmT" },
    { q: "Hvilket band sang 'Elskere i Natten'?", a: "Tøsedrengene", options: ["Tøsedrengene", "TV-2", "Gnags", "Rocazino"] },
    { q: "Hvem sang 'Gi' Mig Danmark Tilbage'?", a: "Kim Larsen", options: ["Kim Larsen", "Shu-bi-dua", "Gasolin'", "Sebastian"] },
    { q: "Hvilket band sang 'Nærmest Lykkelig'?", a: "TV-2", options: ["TV-2", "Tøsedrengene", "Gnags", "Kashmir"], spotify: "https://open.spotify.com/track/5V13p5RZpk6vX03G7Cm5vR" },
    { q: "Hvem sang 'Det' Noget Med Ansen'?", a: "Shu-bi-dua", options: ["Shu-bi-dua", "Kim Larsen", "Gasolin'", "De Nattergale"] },
    { q: "Hvilket dansk band sang 'Rocket Boy'?", a: "Kashmir", options: ["Mew", "Kashmir", "Saybia", "Carpark North"] },
    { q: "Hvem sang 'Engel'?", a: "Nik & Jay", options: ["Nik & Jay", "Rasmus Seebach", "Joey Moe", "Burhan G"] },
    { q: "Hvilket band sang 'This Is My Life'?", a: "Gasolin'", options: ["Gasolin'", "Sort Sol", "D-A-D", "Pretty Maids"], spotify: "https://open.spotify.com/track/20cXLoPJmiZDuDgLLMQP29" },
    { q: "Hvem sang 'Den Jeg Elsker'?", a: "Rasmus Seebach", options: ["Thomas Helmig", "Rasmus Seebach", "Nik & Jay", "Kim Larsen"] },
    { q: "Hvilket band sang 'Sleeping My Day Away'?", a: "D-A-D", options: ["D-A-D", "Pretty Maids", "Sort Sol", "Volbeat"], spotify: "https://open.spotify.com/track/1LfAxXcY6bAAaPZFfk2cWf" },
    { q: "Hvem sang 'Rabalderstræde'?", a: "Gasolin'", options: ["Gasolin'", "Shu-bi-dua", "Kim Larsen", "Steppeulvene"], spotify: "https://open.spotify.com/track/7Ifwo3BqbLtL5q60dV9O0x" },
    { q: "Hvilket band sang 'Langebansen'?", a: "Gnags", options: ["Gnags", "TV-2", "Shu-bi-dua", "Tøsedrengene"] },
    { q: "Hvem sang 'Papirsklip'?", a: "Kim Larsen", options: ["Kim Larsen", "Sebastian", "Lars H.U.G.", "C.V. Jørgensen"] },
    { q: "Hvilket band vandt Eurovision for Danmark i 2000 med 'Fly on the Wings of Love'?", a: "Olsen Brothers", options: ["Olsen Brothers", "Aqua", "Rollo & King", "Tommy Seebach"] },
    { q: "Hvem sang 'Barbie Girl'?", a: "Aqua", options: ["Aqua", "Toy-Box", "Hit'n'Hide", "Tiggy"], spotify: "https://open.spotify.com/track/6SIDRn0OX4I8sGsDa4eCOZ" },
    { q: "Hvilket dansk band sang 'Still Alive'?", a: "Volbeat", options: ["Volbeat", "D-A-D", "Pretty Maids", "Mercyful Fate"] },
    { q: "Hvem sang 'Nattog Til København'?", a: "C.V. Jørgensen", options: ["Kim Larsen", "C.V. Jørgensen", "Sebastian", "Lars H.U.G."] },
    { q: "Hvilket band sang 'Supermarket'?", a: "Shu-bi-dua", options: ["Shu-bi-dua", "Gnags", "Tøsedrengene", "TV-2"] },
    { q: "Hvem sang 'Floden'?", a: "Lars H.U.G.", options: ["Lars H.U.G.", "Kim Larsen", "Sebastian", "Thomas Helmig"] },
    { q: "Hvilket band sang 'Am I Wrong'?", a: "Nico & Vinz", options: ["Lukas Graham", "Nico & Vinz", "MØ", "Outlandish"], spotify: "https://open.spotify.com/track/1fidCEsYlaVE3pHwKCvpFZ" },
    { q: "Hvem sang '7 Years'?", a: "Lukas Graham", options: ["Lukas Graham", "Nico & Vinz", "MØ", "Christopher"], spotify: "https://open.spotify.com/track/5kqIPrATaCc2LqxVWzQGbk" },
    { q: "Hvilket band sang 'Lean On' med Major Lazer?", a: "MØ", options: ["MØ", "Medina", "Aura Dione", "Agnes Obel"] },
    { q: "Hvem sang 'Dansen' med TV-2?", a: "Steffen Brandt", options: ["Steffen Brandt", "Kim Larsen", "Thomas Helmig", "Michael Falch"] },
    { q: "Hvilket band sang 'Let My Children Hear Music'?", a: "Sort Sol", options: ["Sort Sol", "Kashmir", "Mew", "Under Byen"] },
    { q: "Hvem sang 'Sig Du Ka' Li' Mansen'?", a: "Bamses Venner", options: ["Bamses Venner", "Shu-bi-dua", "Gnags", "Kim Larsen"] },
    { q: "Hvilket band sang '156'?", a: ["Mew"], options: ["Mew", "Kashmir", "Carpark North", "Saybia"] },
    { q: "Hvem sang 'Apache'?", a: "Jørgen Ingmann", options: ["Jørgen Ingmann", "The Shadows", "The Spotnicks", "Bent Fabric"] },
    { q: "Hvilket band sang 'Only Shallow' (dansk version)?", a: "Efterklang", options: ["Efterklang", "Under Byen", "Mew", "Sort Sol"] },
    { q: "Hvem sang 'Hvor Ku' Du Tro'?", a: "Anne Linnet", options: ["Anne Linnet", "Sanne Salomonsen", "Lis Sørensen", "Hanne Boel"] }
  ],
  "Film Soundtracks": [
    { q: "Hvilken film er 'Stayin' Alive' af Bee Gees fra?", a: "Saturday Night Fever", options: ["Saturday Night Fever", "Grease", "Dirty Dancing", "Footloose"] },
    { q: "Hvem sang 'Eye of the Tiger' fra Rocky III?", a: "Survivor", options: ["Survivor", "Journey", "Foreigner", "REO Speedwagon"] },
    { q: "Hvilken film bruger 'Danger Zone' af Kenny Loggins?", a: "Top Gun", options: ["Top Gun", "Footloose", "Flashdance", "Beverly Hills Cop"] },
    { q: "Hvem sang 'Ghostbusters' temasangen?", a: "Ray Parker Jr.", options: ["Ray Parker Jr.", "Huey Lewis", "Rick Springfield", "Billy Ocean"] },
    { q: "Hvilken film er 'The Time of My Life' fra?", a: "Dirty Dancing", options: ["Dirty Dancing", "Flashdance", "Footloose", "Grease"] },
    { q: "Hvem sang 'Lose Yourself' fra 8 Mile?", a: "Eminem", options: ["Eminem", "50 Cent", "Jay-Z", "Kanye West"] },
    { q: "Hvilken film er 'Don't You (Forget About Me)' fra?", a: "The Breakfast Club", options: ["The Breakfast Club", "Pretty in Pink", "Sixteen Candles", "Ferris Bueller's Day Off"] },
    { q: "Hvem sang temaet til James Bond-filmen 'Goldfinger'?", a: "Shirley Bassey", options: ["Shirley Bassey", "Tom Jones", "Nancy Sinatra", "Dusty Springfield"] },
    { q: "Hvilken film er 'Hakuna Matata' fra?", a: "Løvernes Konge", options: ["Løvernes Konge", "Aladdin", "Jungle Book", "Tarzan"] },
    { q: "Hvem sang 'Skyfall' til James Bond-filmen?", a: "Adele", options: ["Adele", "Sam Smith", "Billie Eilish", "Alicia Keys"] },
    { q: "Hvilken film er 'Footloose' temasangen fra?", a: "Footloose", options: ["Footloose", "Flashdance", "Dirty Dancing", "Fame"] },
    { q: "Hvem sang 'Maniac' fra Flashdance?", a: "Michael Sembello", options: ["Michael Sembello", "Irene Cara", "Kenny Loggins", "Jennifer Beals"] },
    { q: "Hvilken film bruger 'Mrs. Robinson' af Simon & Garfunkel?", a: "The Graduate", options: ["The Graduate", "Butch Cassidy", "Easy Rider", "Midnight Cowboy"] },
    { q: "Hvem sang 'Let It Go' fra Frozen?", a: "Idina Menzel", options: ["Idina Menzel", "Kristen Bell", "Demi Lovato", "Elsa"] },
    { q: "Hvilken film er 'Shallow' fra?", a: "A Star Is Born", options: ["A Star Is Born", "La La Land", "The Greatest Showman", "Bohemian Rhapsody"] },
    { q: "Hvem komponerede musikken til Star Wars?", a: "John Williams", options: ["John Williams", "Hans Zimmer", "Howard Shore", "James Horner"] },
    { q: "Hvilken film er 'Raindrops Keep Fallin' on My Head' fra?", a: "Butch Cassidy and the Sundance Kid", options: ["Butch Cassidy and the Sundance Kid", "The Graduate", "Easy Rider", "Midnight Cowboy"] },
    { q: "Hvem sang 'Take My Breath Away' fra Top Gun?", a: "Berlin", options: ["Berlin", "Heart", "Bonnie Tyler", "Pat Benatar"] },
    { q: "Hvilken film er 'Everybody's Talkin'' fra?", a: "Midnight Cowboy", options: ["Midnight Cowboy", "Easy Rider", "The Graduate", "Butch Cassidy"] },
    { q: "Hvem komponerede musikken til Ringenes Herre?", a: "Howard Shore", options: ["Howard Shore", "John Williams", "Hans Zimmer", "James Horner"] },
    { q: "Hvilken film er 'Old Time Rock and Roll' forbundet med?", a: "Risky Business", options: ["Risky Business", "Footloose", "The Big Chill", "Back to the Future"] },
    { q: "Hvem sang 'Happy' fra Grusomme Mig 2?", a: "Pharrell Williams", options: ["Pharrell Williams", "Bruno Mars", "Justin Timberlake", "will.i.am"] },
    { q: "Hvilken film er 'Bohemian Rhapsody' af Queen brugt i (berømt bilscene)?", a: "Wayne's World", options: ["Wayne's World", "Bohemian Rhapsody", "Rocketman", "Dazed and Confused"] },
    { q: "Hvem sang 'I Don't Want to Miss a Thing' fra Armageddon?", a: "Aerosmith", options: ["Aerosmith", "Bon Jovi", "Bryan Adams", "Journey"] },
    { q: "Hvilken film er 'The Power of Love' af Huey Lewis fra?", a: "Tilbage til Fremtiden", options: ["Tilbage til Fremtiden", "Top Gun", "Beverly Hills Cop", "Ghostbusters"] },
    { q: "Hvem sang temaet fra Titanic?", a: "Celine Dion", options: ["Celine Dion", "Whitney Houston", "Mariah Carey", "Barbra Streisand"] },
    { q: "Hvilken film er 'A Whole New World' fra?", a: "Aladdin", options: ["Aladdin", "Løvernes Konge", "Den Lille Havfrue", "Skønheden og Udyret"] },
    { q: "Hvem komponerede musikken til Pirates of the Caribbean?", a: "Hans Zimmer", options: ["Hans Zimmer", "John Williams", "Howard Shore", "Danny Elfman"] },
    { q: "Hvilken film er 'Stuck in the Middle with You' berømt brugt i?", a: "Reservoir Dogs", options: ["Reservoir Dogs", "Pulp Fiction", "Kill Bill", "Snatch"] },
    { q: "Hvem sang 'Writing's on the Wall' til Spectre?", a: "Sam Smith", options: ["Sam Smith", "Adele", "Ed Sheeran", "Chris Cornell"] },
    { q: "Hvilken film bruger 'Immigrant Song' af Led Zeppelin i åbningsscenen?", a: "Thor: Ragnarok", options: ["Thor: Ragnarok", "Shrek", "School of Rock", "Zeppelin!"] }
  ],
  "Gæt Sangteksten": [
    { q: "'Is this the real life? Is this just fantasy?'", a: "Bohemian Rhapsody – Queen", options: ["Bohemian Rhapsody – Queen", "Comfortably Numb – Pink Floyd", "Space Oddity – David Bowie", "Imagine – John Lennon"] },
    { q: "'Ground control to Major Tom...'", a: "Space Oddity – David Bowie", options: ["Rocket Man – Elton John", "Space Oddity – David Bowie", "Starman – David Bowie", "Life on Mars – David Bowie"] },
    { q: "'Hello, is it me you're looking for?'", a: "Hello – Lionel Richie", options: ["Hello – Adele", "Hello – Lionel Richie", "Is This Love – Bob Marley", "Careless Whisper – George Michael"] },
    { q: "'We're no strangers to love, you know the rules and so do I'", a: "Never Gonna Give You Up – Rick Astley", options: ["Never Gonna Give You Up – Rick Astley", "Take On Me – a-ha", "Together Forever – Rick Astley", "Careless Whisper – George Michael"] },
    { q: "'Just a small town girl, livin' in a lonely world'", a: "Don't Stop Believin' – Journey", options: ["Don't Stop Believin' – Journey", "Livin' on a Prayer – Bon Jovi", "Faithfully – Journey", "Open Arms – Journey"] },
    { q: "'Midt om natten, når du ka' høre havets stemmer'", a: "Midt Om Natten – Kim Larsen", options: ["Midt Om Natten – Kim Larsen", "Papirsklip – Kim Larsen", "Køb Banansen – Kim Larsen", "Om Lidt – Kim Larsen"] },
    { q: "'I see a red door and I want it painted black'", a: "Paint It Black – The Rolling Stones", options: ["Paint It Black – The Rolling Stones", "Sympathy for the Devil – The Rolling Stones", "Black Dog – Led Zeppelin", "Back in Black – AC/DC"] },
    { q: "'Here we are now, entertain us'", a: "Smells Like Teen Spirit – Nirvana", options: ["Smells Like Teen Spirit – Nirvana", "Lithium – Nirvana", "Come as You Are – Nirvana", "In Bloom – Nirvana"] },
    { q: "'I want to ride my bicycle, I want to ride my bike'", a: "Bicycle Race – Queen", options: ["Bicycle Race – Queen", "Tour de France – Kraftwerk", "Daydream Believer – The Monkees", "Bohemian Rhapsody – Queen"] },
    { q: "'Du skal si' ka' du li' mansen, for mansen den ka' li' dig'", a: "Sig Du Ka' Li' Mansen – Bamses Venner", options: ["Sig Du Ka' Li' Mansen – Bamses Venner", "Vimmersvansen – Shu-bi-dua", "Langebansen – Gnags", "Bamse – Bamses Venner"] },
    { q: "'Imagine there's no heaven, it's easy if you try'", a: "Imagine – John Lennon", options: ["Imagine – John Lennon", "Let It Be – The Beatles", "Hey Jude – The Beatles", "Give Peace a Chance – John Lennon"] },
    { q: "'Is this love that I'm feeling?'", a: "Is This Love – Whitesnake", options: ["Is This Love – Whitesnake", "Is This Love – Bob Marley", "I Want to Know What Love Is – Foreigner", "What Is Love – Haddaway"] },
    { q: "'Every move you make, every bond you break'", a: "Every Breath You Take – The Police", options: ["Every Breath You Take – The Police", "I'll Be Watching You – Sting", "Roxanne – The Police", "Don't Stand So Close to Me – The Police"] },
    { q: "'I come from a land down under'", a: "Down Under – Men at Work", options: ["Down Under – Men at Work", "Waltzing Matilda – Traditional", "Beds Are Burning – Midnight Oil", "Working Class Man – Jimmy Barnes"] },
    { q: "'Today is gonna be the day that they're gonna throw it back to you'", a: "Wonderwall – Oasis", options: ["Wonderwall – Oasis", "Don't Look Back in Anger – Oasis", "Champagne Supernova – Oasis", "Bitter Sweet Symphony – The Verve"] },
    { q: "'Rabalderstræde — det strøg den ener, de ler og griner'", a: "Rabalderstræde – Gasolin'", options: ["Rabalderstræde – Gasolin'", "Kvinde Min – Gasolin'", "This Is My Life – Gasolin'", "Langebansen – Gnags"] },
    { q: "'We will, we will rock you!'", a: "We Will Rock You – Queen", options: ["We Will Rock You – Queen", "We Are the Champions – Queen", "Another One Bites the Dust – Queen", "Thunderstruck – AC/DC"] },
    { q: "'I'm a creep, I'm a weirdo'", a: "Creep – Radiohead", options: ["Creep – Radiohead", "Loser – Beck", "Basket Case – Green Day", "Paranoid Android – Radiohead"] },
    { q: "'You may say I'm a dreamer, but I'm not the only one'", a: "Imagine – John Lennon", options: ["Imagine – John Lennon", "Dream On – Aerosmith", "Dreamer – Supertramp", "Daydream Believer – The Monkees"] },
    { q: "'Nærmest lykkelig gik jeg ned ad gaden'", a: "Nærmest Lykkelig – TV-2", options: ["Nærmest Lykkelig – TV-2", "Elskere i Natten – Tøsedrengene", "Floden – Lars H.U.G.", "Sommer i Europa – Thomas Helmig"] },
    { q: "'SOS, please someone help me'", a: "SOS – ABBA", options: ["SOS – ABBA", "Help! – The Beatles", "Somebody to Love – Queen", "SOS – Rihanna"] },
    { q: "'What is love? Baby don't hurt me'", a: "What Is Love – Haddaway", options: ["What Is Love – Haddaway", "I Want to Know What Love Is – Foreigner", "Tainted Love – Soft Cell", "Crazy Little Thing Called Love – Queen"] },
    { q: "'On a dark desert highway, cool wind in my hair'", a: "Hotel California – Eagles", options: ["Hotel California – Eagles", "Desperado – Eagles", "Take It Easy – Eagles", "Peaceful Easy Feeling – Eagles"] },
    { q: "'And I would walk 500 miles'", a: "I'm Gonna Be (500 Miles) – The Proclaimers", options: ["I'm Gonna Be (500 Miles) – The Proclaimers", "Walk of Life – Dire Straits", "Walking on Sunshine – Katrina and the Waves", "Walk This Way – Aerosmith"] },
    { q: "'It's the final countdown!'", a: "The Final Countdown – Europe", options: ["The Final Countdown – Europe", "Jump – Van Halen", "Rock You Like a Hurricane – Scorpions", "Run to the Hills – Iron Maiden"] },
    { q: "'Somebody once told me the world is gonna roll me'", a: "All Star – Smash Mouth", options: ["All Star – Smash Mouth", "Walking on the Sun – Smash Mouth", "Tubthumping – Chumbawamba", "MMMBop – Hanson"] },
    { q: "'Under the bridge downtown, is where I drew some blood'", a: "Under the Bridge – Red Hot Chili Peppers", options: ["Under the Bridge – Red Hot Chili Peppers", "Californication – RHCP", "Give It Away – RHCP", "Scar Tissue – RHCP"] },
    { q: "'Mama, just killed a man, put a gun against his head'", a: "Bohemian Rhapsody – Queen", options: ["Bohemian Rhapsody – Queen", "The Show Must Go On – Queen", "I Want to Break Free – Queen", "Killer Queen – Queen"] },
    { q: "'I bless the rains down in Africa'", a: "Africa – Toto", options: ["Africa – Toto", "Rosanna – Toto", "In the Air Tonight – Phil Collins", "The Lion Sleeps Tonight – The Tokens"] },
    { q: "'Smuk som et stjerneskud — og jeg ta'r mit gode tøj på'", a: "Smuk Som Et Stjerneskud – Shu-bi-dua", options: ["Smuk Som Et Stjerneskud – Shu-bi-dua", "Det' Noget Med Ansen – Shu-bi-dua", "Sexchansen – Shu-bi-dua", "Supermarket – Shu-bi-dua"] },
    { q: "'I've got my mind set on you'", a: "Got My Mind Set on You – George Harrison", options: ["Got My Mind Set on You – George Harrison", "My Sweet Lord – George Harrison", "Let It Be – The Beatles", "Come Together – The Beatles"] }
  ],
  "One-Hit Wonders": [
    { q: "Hvem sang 'Take On Me' — var de one-hit wonders i USA?", a: "a-ha", options: ["a-ha", "Tears for Fears", "Men at Work", "Kajagoogoo"], spotify: "https://open.spotify.com/track/2WfaOiMkCvy7F5fcp2zZ8L" },
    { q: "Hvem sang 'Tainted Love' i 1981?", a: "Soft Cell", options: ["Soft Cell", "Depeche Mode", "Erasure", "Yazoo"], spotify: "https://open.spotify.com/track/58E1XVmZTODC67YNjneuXM" },
    { q: "Hvem sang 'Come on Eileen'?", a: "Dexys Midnight Runners", options: ["Dexys Midnight Runners", "Madness", "The Specials", "The Smiths"], spotify: "https://open.spotify.com/track/76JUY8FZxTTjznKIPv57f2" },
    { q: "Hvem sang 'Video Killed the Radio Star'?", a: "The Buggles", options: ["The Buggles", "Gary Numan", "Kraftwerk", "Devo"], spotify: "https://open.spotify.com/track/1OFJktKPHOx0M8hTnJABjl" },
    { q: "Hvem sang 'Mambo No. 5'?", a: "Lou Bega", options: ["Lou Bega", "Ricky Martin", "Enrique Iglesias", "Marc Anthony"], spotify: "https://open.spotify.com/track/5H4jRGIxGoykrQ2MKwazII" },
    { q: "Hvem sang '99 Luftballons'?", a: "Nena", options: ["Nena", "Nina Hagen", "Kraftwerk", "Falco"], spotify: "https://open.spotify.com/track/2tpWsVSagGXKPCkp2yzR9e" },
    { q: "Hvem sang 'Macarena'?", a: "Los del Río", options: ["Los del Río", "Ricky Martin", "Shakira", "Enrique Iglesias"], spotify: "https://open.spotify.com/track/5v4GgrXPMGHl4UXsAkx2V5" },
    { q: "Hvem sang 'Who Let the Dogs Out'?", a: "Baha Men", options: ["Baha Men", "Crazy Town", "Smash Mouth", "LFO"], spotify: "https://open.spotify.com/track/1X7YFKH8dAcqUOdXwLGA3S" },
    { q: "Hvem sang 'Ice Ice Baby'?", a: "Vanilla Ice", options: ["Vanilla Ice", "MC Hammer", "Snow", "Kriss Kross"], spotify: "https://open.spotify.com/track/2Kh4y6bRBKJgCQMBnfl00o" },
    { q: "Hvem sang 'Tubthumping (I Get Knocked Down)'?", a: "Chumbawamba", options: ["Chumbawamba", "Spacehog", "Wheatus", "Lit"], spotify: "https://open.spotify.com/track/2JLRcAkPB8JZIIohZarVTr" },
    { q: "Hvem sang 'Breakfast at Tiffany's'?", a: "Deep Blue Something", options: ["Deep Blue Something", "Toad the Wet Sprocket", "Gin Blossoms", "Fastball"], spotify: "https://open.spotify.com/track/28FJMlLUu9NHuwlZWFKDn7" },
    { q: "Hvem sang 'Steal My Sunshine'?", a: "Len", options: ["Len", "Fastball", "Lit", "Eagle-Eye Cherry"], spotify: "https://open.spotify.com/track/4yl5FPJQcZcKXOpKvep8Wz" },
    { q: "Hvem sang 'Teenage Dirtbag'?", a: "Wheatus", options: ["Wheatus", "Lit", "Blink-182", "Sum 41"], spotify: "https://open.spotify.com/track/1IW4psyxKV1vfttYkhMJhE" },
    { q: "Hvem sang 'Walking on Sunshine'?", a: "Katrina and the Waves", options: ["Katrina and the Waves", "Cyndi Lauper", "The Go-Go's", "Belinda Carlisle"], spotify: "https://open.spotify.com/track/05wIrZSwuaVWhcv5FfqeH0" },
    { q: "Hvem sang 'Spirit in the Sky'?", a: "Norman Greenbaum", options: ["Norman Greenbaum", "Creedence Clearwater Revival", "The Byrds", "Steppenwolf"], spotify: "https://open.spotify.com/track/7cjlfxBKYXfzHTJnlbGQKi" },
    { q: "Hvem sang 'Blue (Da Ba Dee)'?", a: "Eiffel 65", options: ["Eiffel 65", "Aqua", "Vengaboys", "Toy-Box"], spotify: "https://open.spotify.com/track/58UJMbPVaSO6UoahTTlKwi" },
    { q: "Hvem sang 'Rock Me Amadeus'?", a: "Falco", options: ["Falco", "Nena", "Kraftwerk", "a-ha"], spotify: "https://open.spotify.com/track/3TKjL0waU4oByYQMXfDgj8" },
    { q: "Hvem sang 'Safety Dance'?", a: "Men Without Hats", options: ["Men Without Hats", "Devo", "Thomas Dolby", "Kajagoogoo"], spotify: "https://open.spotify.com/track/79aVoH3TLnv1itGQz7PSvN" },
    { q: "Hvem sang 'Somebody That I Used to Know'?", a: "Gotye", options: ["Gotye", "Foster the People", "Fun.", "Passion Pit"], spotify: "https://open.spotify.com/track/1qDrWA6lyx8cLECdZE7TV7" },
    { q: "Hvem sang 'Crazy Town' — 'Butterfly'?", a: "Crazy Town", options: ["Crazy Town", "Papa Roach", "Limp Bizkit", "Incubus"] },
    { q: "Hvem sang 'Flagpole Sitta'?", a: "Harvey Danger", options: ["Harvey Danger", "Lit", "Fastball", "Spacehog"], spotify: "https://open.spotify.com/track/3CtJzDliSOMSJETh9aJMaH" },
    { q: "Hvem sang 'The Way'?", a: "Fastball", options: ["Fastball", "Third Eye Blind", "Matchbox Twenty", "Deep Blue Something"], spotify: "https://open.spotify.com/track/0x9bpnlRgLRCvSJf0FTIlF" },
    { q: "Hvem sang 'Funkytown'?", a: "Lipps Inc.", options: ["Lipps Inc.", "Kool & the Gang", "Earth, Wind & Fire", "Chic"], spotify: "https://open.spotify.com/track/29UivbAIMHxhMzaKIjscbO" },
    { q: "Hvem sang 'In the Year 2525'?", a: "Zager and Evans", options: ["Zager and Evans", "The Buggles", "Gary Numan", "Devo"], spotify: "https://open.spotify.com/track/7v9gfBJnCmi1y7xMBaJFFS" },
    { q: "Hvem sang 'My Sharona'?", a: "The Knack", options: ["The Knack", "Blondie", "The Cars", "The Police"], spotify: "https://open.spotify.com/track/4TkTb2FDJc0mtU9YIAhKyI" },
    { q: "Hvem sang 'Stacy's Mom'?", a: "Fountains of Wayne", options: ["Fountains of Wayne", "Wheatus", "Blink-182", "Jimmy Eat World"], spotify: "https://open.spotify.com/track/1Bpc7GBHbqWEwEONaFQqkC" },
    { q: "Hvem sang 'Save Tonight'?", a: "Eagle-Eye Cherry", options: ["Eagle-Eye Cherry", "Jack Johnson", "Jason Mraz", "Ben Harper"], spotify: "https://open.spotify.com/track/5iFMVaakY6zxZkixYfjFj4" },
    { q: "Hvem sang 'Kung Fu Fighting'?", a: "Carl Douglas", options: ["Carl Douglas", "Hot Chocolate", "KC and the Sunshine Band", "The Trammps"], spotify: "https://open.spotify.com/track/2lNFWUrxuNaQsf5I1pjTPO" },
    { q: "Hvem sang 'Mickey'?", a: "Toni Basil", options: ["Toni Basil", "Cyndi Lauper", "Go-Go's", "The Bangles"], spotify: "https://open.spotify.com/track/3B1BLBHNHR7zJQYHkZ3odB" },
    { q: "Hvem sang 'Brimful of Asha'?", a: "Cornershop", options: ["Cornershop", "Chumbawamba", "Morcheeba", "Massive Attack"], spotify: "https://open.spotify.com/track/0Oa7eQlG17qWmkPqsXbABt" },
    { q: "Hvem sang 'You Get What You Give'?", a: "New Radicals", options: ["New Radicals", "Semisonic", "Fastball", "Third Eye Blind"], spotify: "https://open.spotify.com/track/3HVsb1K5VWnm55v2szdMjd" }
  ],
  "70'er Disco & Funk": [
    { q: "Hvem sang 'Stayin' Alive'?", a: "Bee Gees", options: ["Bee Gees", "ABBA", "KC and the Sunshine Band", "Donna Summer"] },
    { q: "Hvilket band sang 'September'?", a: "Earth, Wind & Fire", options: ["Earth, Wind & Fire", "Kool & the Gang", "Chic", "The Commodores"] },
    { q: "Hvem sang 'I Will Survive'?", a: "Gloria Gaynor", options: ["Gloria Gaynor", "Donna Summer", "Diana Ross", "Sister Sledge"] },
    { q: "Hvilket band sang 'Le Freak'?", a: "Chic", options: ["Chic", "KC and the Sunshine Band", "Earth, Wind & Fire", "Bee Gees"] },
    { q: "Hvem sang 'Hot Stuff'?", a: "Donna Summer", options: ["Donna Summer", "Gloria Gaynor", "Diana Ross", "Cher"] },
    { q: "Hvilket band sang 'Dancing Queen'?", a: "ABBA", options: ["ABBA", "Bee Gees", "Boney M", "The Carpenters"] },
    { q: "Hvem sang 'Superstition'?", a: "Stevie Wonder", options: ["Stevie Wonder", "James Brown", "Marvin Gaye", "Curtis Mayfield"] },
    { q: "Hvilket band sang 'Get Up (I Feel Like Being a) Sex Machine'?", a: "James Brown", options: ["James Brown", "Parliament", "Sly & the Family Stone", "Earth, Wind & Fire"] },
    { q: "Hvem sang 'Rasputin'?", a: "Boney M", options: ["Boney M", "ABBA", "Bee Gees", "Village People"] },
    { q: "Hvilket band sang 'Y.M.C.A.'?", a: "Village People", options: ["Village People", "Bee Gees", "Boney M", "Chic"] },
    { q: "Hvem sang 'Disco Inferno'?", a: "The Trammps", options: ["The Trammps", "Kool & the Gang", "KC and the Sunshine Band", "Bee Gees"] },
    { q: "Hvilket band sang 'That's the Way (I Like It)'?", a: "KC and the Sunshine Band", options: ["KC and the Sunshine Band", "Bee Gees", "Earth, Wind & Fire", "Kool & the Gang"] },
    { q: "Hvem sang 'We Are Family'?", a: "Sister Sledge", options: ["Sister Sledge", "The Pointer Sisters", "Chic", "En Vogue"] },
    { q: "Hvilket band sang 'Celebration'?", a: "Kool & the Gang", options: ["Kool & the Gang", "Earth, Wind & Fire", "KC and the Sunshine Band", "Chic"] },
    { q: "Hvem sang 'What's Going On'?", a: "Marvin Gaye", options: ["Marvin Gaye", "Stevie Wonder", "Curtis Mayfield", "Al Green"] },
    { q: "Hvilket band sang 'Play That Funky Music'?", a: "Wild Cherry", options: ["Wild Cherry", "KC and the Sunshine Band", "Parliament", "Ohio Players"] },
    { q: "Hvem sang 'I Feel Love'?", a: "Donna Summer", options: ["Donna Summer", "Gloria Gaynor", "Grace Jones", "Blondie"] },
    { q: "Hvilket band sang 'Give Up the Funk (Tear the Roof off the Sucker)'?", a: "Parliament", options: ["Parliament", "Funkadelic", "Earth, Wind & Fire", "James Brown"] },
    { q: "Hvem sang 'Let's Get It On'?", a: "Marvin Gaye", options: ["Marvin Gaye", "Barry White", "Al Green", "Teddy Pendergrass"] },
    { q: "Hvilket band sang 'Waterloo'?", a: "ABBA", options: ["ABBA", "Boney M", "Bee Gees", "Blondie"] },
    { q: "Hvem sang 'Shaft' (temasangen)?", a: "Isaac Hayes", options: ["Isaac Hayes", "Curtis Mayfield", "James Brown", "Barry White"] },
    { q: "Hvilket band sang 'Brick House'?", a: "The Commodores", options: ["The Commodores", "Earth, Wind & Fire", "Kool & the Gang", "Ohio Players"] },
    { q: "Hvem sang 'Car Wash'?", a: "Rose Royce", options: ["Rose Royce", "The Trammps", "KC and the Sunshine Band", "Wild Cherry"] },
    { q: "Hvilket band sang 'Heart of Glass'?", a: "Blondie", options: ["Blondie", "The Go-Go's", "Donna Summer", "Grace Jones"] },
    { q: "Hvem sang 'Night Fever'?", a: "Bee Gees", options: ["Bee Gees", "ABBA", "Donna Summer", "KC and the Sunshine Band"] },
    { q: "Hvilket band sang 'Boogie Wonderland'?", a: "Earth, Wind & Fire", options: ["Earth, Wind & Fire", "Chic", "Bee Gees", "Kool & the Gang"] },
    { q: "Hvem sang 'Rivers of Babylon'?", a: "Boney M", options: ["Boney M", "Bob Marley", "Jimmy Cliff", "UB40"] },
    { q: "Hvilket band sang 'Good Times'?", a: "Chic", options: ["Chic", "Kool & the Gang", "Earth, Wind & Fire", "The Commodores"] },
    { q: "Hvem sang 'You Should Be Dancing'?", a: "Bee Gees", options: ["Bee Gees", "Donna Summer", "KC and the Sunshine Band", "Gloria Gaynor"] },
    { q: "Hvilket band sang 'Ring My Bell'?", a: "Anita Ward", options: ["Anita Ward", "Donna Summer", "Gloria Gaynor", "Sister Sledge"] },
    { q: "Hvem sang 'Le Freak, c'est chic'?", a: "Chic", options: ["Chic", "Bee Gees", "Donna Summer", "Village People"] }
  ],
  "Hvem Er Bandet?": [
    { q: "Mick Jagger er forsanger i hvilket band?", a: "The Rolling Stones", options: ["The Rolling Stones", "The Beatles", "Led Zeppelin", "The Who"] },
    { q: "Bono er forsanger i hvilket band?", a: "U2", options: ["Coldplay", "U2", "R.E.M.", "The Verve"] },
    { q: "Freddie Mercury var forsanger i?", a: "Queen", options: ["Queen", "Led Zeppelin", "The Who", "Pink Floyd"] },
    { q: "Kurt Cobain var forsanger i?", a: "Nirvana", options: ["Pearl Jam", "Nirvana", "Soundgarden", "Alice in Chains"] },
    { q: "Axl Rose er forsanger i?", a: "Guns N' Roses", options: ["Guns N' Roses", "Mötley Crüe", "Poison", "Def Leppard"] },
    { q: "Robert Plant var forsanger i?", a: "Led Zeppelin", options: ["Led Zeppelin", "Deep Purple", "Black Sabbath", "The Who"] },
    { q: "Dave Grohl var trommeslager i Nirvana — hvilket band startede han derefter?", a: "Foo Fighters", options: ["Foo Fighters", "Queens of the Stone Age", "Them Crooked Vultures", "Audioslave"] },
    { q: "Lars Ulrich er trommeslager i?", a: "Metallica", options: ["Metallica", "Megadeth", "Slayer", "Anthrax"] },
    { q: "Roger Waters var bassist og sangskriver i?", a: "Pink Floyd", options: ["Pink Floyd", "Genesis", "Yes", "King Crimson"] },
    { q: "Ozzy Osbourne var forsanger i?", a: "Black Sabbath", options: ["Black Sabbath", "Deep Purple", "Judas Priest", "Iron Maiden"] },
    { q: "Kim Larsen var forsanger i hvilket tidligt dansk band?", a: "Gasolin'", options: ["Gasolin'", "Shu-bi-dua", "Gnags", "Sort Sol"] },
    { q: "Thom Yorke er forsanger i?", a: "Radiohead", options: ["Radiohead", "Muse", "Coldplay", "Arctic Monkeys"] },
    { q: "Liam Gallagher er forsanger i?", a: "Oasis", options: ["Blur", "Oasis", "Pulp", "The Verve"] },
    { q: "Bruce Dickinson er forsanger i?", a: "Iron Maiden", options: ["Iron Maiden", "Judas Priest", "Motörhead", "Saxon"] },
    { q: "Anthony Kiedis er forsanger i?", a: "Red Hot Chili Peppers", options: ["Red Hot Chili Peppers", "Rage Against the Machine", "Jane's Addiction", "Primus"] },
    { q: "Jon Bon Jovi er forsanger i?", a: "Bon Jovi", options: ["Bon Jovi", "Def Leppard", "Whitesnake", "Journey"] },
    { q: "Chris Martin er forsanger i?", a: "Coldplay", options: ["Coldplay", "Radiohead", "Keane", "Snow Patrol"] },
    { q: "Eddie Vedder er forsanger i?", a: "Pearl Jam", options: ["Pearl Jam", "Nirvana", "Soundgarden", "Temple of the Dog"] },
    { q: "Angus Young spiller guitar i?", a: "AC/DC", options: ["AC/DC", "Motörhead", "Judas Priest", "Iron Maiden"] },
    { q: "Steffen Brandt er forsanger i?", a: "TV-2", options: ["TV-2", "Tøsedrengene", "Gnags", "Kashmir"] },
    { q: "Jesper Binzer er forsanger i?", a: "D-A-D", options: ["D-A-D", "Volbeat", "Pretty Maids", "Sort Sol"] },
    { q: "Michael Poulsen er forsanger i?", a: "Volbeat", options: ["Volbeat", "D-A-D", "Pretty Maids", "Dizzy Mizz Lizzy"] },
    { q: "Matt Bellamy er forsanger i?", a: "Muse", options: ["Muse", "Radiohead", "Coldplay", "Placebo"] },
    { q: "Robert Smith er forsanger i?", a: "The Cure", options: ["The Cure", "Siouxsie and the Banshees", "Joy Division", "Bauhaus"] },
    { q: "Sting var forsanger i?", a: "The Police", options: ["The Police", "Dire Straits", "U2", "Talking Heads"] },
    { q: "Dave Gahan er forsanger i?", a: "Depeche Mode", options: ["Depeche Mode", "New Order", "Pet Shop Boys", "Erasure"] },
    { q: "Michael Stipe var forsanger i?", a: "R.E.M.", options: ["R.E.M.", "The Smiths", "U2", "Talking Heads"] },
    { q: "Phil Collins var forsanger og trommeslager i?", a: "Genesis", options: ["Genesis", "Pink Floyd", "Yes", "King Crimson"] },
    { q: "Mark Knopfler var forsanger og guitarist i?", a: "Dire Straits", options: ["Dire Straits", "The Police", "U2", "Talking Heads"] },
    { q: "Joey Ramone var forsanger i?", a: "Ramones", options: ["Ramones", "The Clash", "Sex Pistols", "Blondie"] },
    { q: "Debbie Harry var forsanger i?", a: "Blondie", options: ["Blondie", "The Go-Go's", "The Pretenders", "Siouxsie and the Banshees"] }
  ],
  "2000'er & Nyere": [
    { q: "Hvem sang 'Crazy in Love' i 2003?", a: "Beyoncé", options: ["Beyoncé", "Rihanna", "Alicia Keys", "Christina Aguilera"], spotify: "https://open.spotify.com/track/5IVuqXILoxVWvWEPm82Jxr" },
    { q: "Hvilket band sang 'Mr. Brightside'?", a: "The Killers", options: ["The Killers", "Arctic Monkeys", "Franz Ferdinand", "Bloc Party"], spotify: "https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B" },
    { q: "Hvem sang 'Rolling in the Deep'?", a: "Adele", options: ["Adele", "Amy Winehouse", "Florence Welch", "Duffy"], spotify: "https://open.spotify.com/track/1c8gk2PeTE04A1pIDH9YMk" },
    { q: "Hvilket band sang 'I Bet You Look Good on the Dancefloor'?", a: "Arctic Monkeys", options: ["Arctic Monkeys", "The Killers", "Franz Ferdinand", "Kaiser Chiefs"], spotify: "https://open.spotify.com/track/3DQVk1DP0lczAYsdhfBmkU" },
    { q: "Hvem sang 'Rehab'?", a: "Amy Winehouse", options: ["Amy Winehouse", "Adele", "Duffy", "Lily Allen"], spotify: "https://open.spotify.com/track/1L5tZi0izXsi5Kk5OJf4W0" },
    { q: "Hvilket band sang 'Clocks'?", a: "Coldplay", options: ["Coldplay", "Keane", "Snow Patrol", "Travis"], spotify: "https://open.spotify.com/track/0BCPKOYdS2jbQ8iyB56Cey" },
    { q: "Hvem sang 'Poker Face'?", a: "Lady Gaga", options: ["Lady Gaga", "Katy Perry", "Rihanna", "Ke$ha"], spotify: "https://open.spotify.com/track/1QV6tiMFM6fSOKOGLMHYYg" },
    { q: "Hvilket band sang 'Seven Nation Army'?", a: "The White Stripes", options: ["The White Stripes", "The Black Keys", "The Strokes", "Queens of the Stone Age"], spotify: "https://open.spotify.com/track/3dPQuX8Gs42Y7b454ybpMR" },
    { q: "Hvem sang 'Umbrella'?", a: "Rihanna", options: ["Rihanna", "Beyoncé", "Alicia Keys", "Lady Gaga"], spotify: "https://open.spotify.com/track/49FYlytm3dAAraYgpoJZux" },
    { q: "Hvilket band sang 'Chop Suey!'?", a: "System of a Down", options: ["System of a Down", "Slipknot", "Korn", "Linkin Park"], spotify: "https://open.spotify.com/track/4GIkc2oLkb5jlfbHJXoJpC" },
    { q: "Hvem sang 'Get Lucky'?", a: "Daft Punk ft. Pharrell Williams", options: ["Daft Punk ft. Pharrell Williams", "Calvin Harris", "David Guetta", "Avicii"], spotify: "https://open.spotify.com/track/69kOkLUCkxIZYexIgSG8rq" },
    { q: "Hvilket band sang 'In the End'?", a: "Linkin Park", options: ["Linkin Park", "Limp Bizkit", "Papa Roach", "Evanescence"], spotify: "https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq" },
    { q: "Hvem sang 'Uptown Funk'?", a: "Mark Ronson ft. Bruno Mars", options: ["Mark Ronson ft. Bruno Mars", "Justin Timberlake", "Pharrell Williams", "Jason Derulo"], spotify: "https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS" },
    { q: "Hvilket band sang 'Somebody Told Me'?", a: "The Killers", options: ["The Killers", "Arctic Monkeys", "Franz Ferdinand", "The Strokes"], spotify: "https://open.spotify.com/track/4MkLOmkOlFM0JnxNSHMiqm" },
    { q: "Hvem sang 'Shape of You'?", a: "Ed Sheeran", options: ["Ed Sheeran", "Sam Smith", "James Bay", "Shawn Mendes"], spotify: "https://open.spotify.com/track/7qiZfU4dY1lWllzX7mPBI3" },
    { q: "Hvilket band sang 'Take Me Out'?", a: "Franz Ferdinand", options: ["Franz Ferdinand", "The Killers", "Arctic Monkeys", "Interpol"], spotify: "https://open.spotify.com/track/46s59bHbMjLw3MnuVrAIU5" },
    { q: "Hvem sang 'Bad Guy'?", a: "Billie Eilish", options: ["Billie Eilish", "Lorde", "Halsey", "Dua Lipa"], spotify: "https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m" },
    { q: "Hvilket band sang 'Use Somebody'?", a: "Kings of Leon", options: ["Kings of Leon", "The Killers", "Coldplay", "Muse"], spotify: "https://open.spotify.com/track/71e07cRkyTMG6VGj6G3Mio" },
    { q: "Hvem sang 'Blinding Lights'?", a: "The Weeknd", options: ["The Weeknd", "Bruno Mars", "Daft Punk", "Calvin Harris"], spotify: "https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b" },
    { q: "Hvilket band sang 'Do I Wanna Know?'?", a: "Arctic Monkeys", options: ["Arctic Monkeys", "The Black Keys", "Tame Impala", "Royal Blood"], spotify: "https://open.spotify.com/track/5FVd6KXrgO9B3JPmGOFSCb" },
    { q: "Hvem sang 'Someone Like You'?", a: "Adele", options: ["Adele", "Sam Smith", "Amy Winehouse", "Lana Del Rey"], spotify: "https://open.spotify.com/track/1zwMYTA5nlNjZxYrvBB2pV" },
    { q: "Hvilket band sang 'Feel Good Inc.'?", a: "Gorillaz", options: ["Gorillaz", "Blur", "Radiohead", "Massive Attack"], spotify: "https://open.spotify.com/track/0d28khcov6AiegSCpG5TuT" },
    { q: "Hvem sang 'Hips Don't Lie'?", a: "Shakira", options: ["Shakira", "Jennifer Lopez", "Beyoncé", "Rihanna"], spotify: "https://open.spotify.com/track/3ZFTkvIE7kyPt6Nu3PEa7V" },
    { q: "Hvilket band sang 'Radioactive'?", a: "Imagine Dragons", options: ["Imagine Dragons", "OneRepublic", "Bastille", "Twenty One Pilots"], spotify: "https://open.spotify.com/track/69yfbpvmkIaB3KjGPJhtstg" },
    { q: "Hvem sang 'Levitating'?", a: "Dua Lipa", options: ["Dua Lipa", "Lizzo", "Doja Cat", "Ariana Grande"], spotify: "https://open.spotify.com/track/39LLxExYz6ewLAo9CYQY9a" },
    { q: "Hvilket band sang 'Stressed Out'?", a: "Twenty One Pilots", options: ["Twenty One Pilots", "Imagine Dragons", "Bastille", "Panic! at the Disco"], spotify: "https://open.spotify.com/track/3CRDbSIZ4r5MsZ0YwxuEkn" },
    { q: "Hvem sang 'Royals'?", a: "Lorde", options: ["Lorde", "Billie Eilish", "Halsey", "Lana Del Rey"], spotify: "https://open.spotify.com/track/2dLLR6qlu5UJ5gk0dKz0h3" },
    { q: "Hvilket band sang 'The Pretender'?", a: "Foo Fighters", options: ["Foo Fighters", "Queens of the Stone Age", "Muse", "Green Day"], spotify: "https://open.spotify.com/track/7x8dCjCr0x6x2lXKujYD34" },
    { q: "Hvem sang 'Old Town Road'?", a: "Lil Nas X", options: ["Lil Nas X", "Post Malone", "Travis Scott", "Drake"], spotify: "https://open.spotify.com/track/2YlZnhMz4MRAqh0Nblpkn1" },
    { q: "Hvilket band sang 'Pompeii'?", a: "Bastille", options: ["Bastille", "Imagine Dragons", "Twenty One Pilots", "OneRepublic"], spotify: "https://open.spotify.com/track/1KxwZRCIyUOoOaRFkKIeb7" },
    { q: "Hvem sang 'Wake Me Up'?", a: "Avicii", options: ["Avicii", "David Guetta", "Calvin Harris", "Tiësto"], spotify: "https://open.spotify.com/track/0nrRP2bk19rLc0orkWPQk2" }
  ],
  "Album Covers": [
    { q: "Hvilket albums cover viser et prisme der spreder lys i en regnbue?", a: "The Dark Side of the Moon – Pink Floyd", options: ["The Dark Side of the Moon – Pink Floyd", "Wish You Were Here – Pink Floyd", "Abbey Road – The Beatles", "Houses of the Holy – Led Zeppelin"] },
    { q: "Hvilket album har fire personer der krydser en fodgængerovergang?", a: "Abbey Road – The Beatles", options: ["Abbey Road – The Beatles", "Let It Be – The Beatles", "The Dark Side of the Moon – Pink Floyd", "London Calling – The Clash"] },
    { q: "Hvilket album viser en brændende mand der giver hånd?", a: "Wish You Were Here – Pink Floyd", options: ["Wish You Were Here – Pink Floyd", "The Dark Side of the Moon – Pink Floyd", "The Wall – Pink Floyd", "Animals – Pink Floyd"] },
    { q: "Hvilket album viser en baby der svømmer efter en dollarseddel?", a: "Nevermind – Nirvana", options: ["Nevermind – Nirvana", "In Utero – Nirvana", "Ten – Pearl Jam", "Bleach – Nirvana"] },
    { q: "Hvilket album har en banan på coveret (Andy Warhol design)?", a: "The Velvet Underground & Nico", options: ["The Velvet Underground & Nico", "Sticky Fingers – The Rolling Stones", "Yellow Submarine – The Beatles", "Banana – The Dandy Warhols"] },
    { q: "Hvilket album viser en stor mund med tungen ude (logo)?", a: "Sticky Fingers – The Rolling Stones", options: ["Sticky Fingers – The Rolling Stones", "Let It Bleed – The Rolling Stones", "Exile on Main St. – The Rolling Stones", "Some Girls – The Rolling Stones"] },
    { q: "Hvilket album viser en Hindenburg-luftskib i flammer?", a: "Led Zeppelin I", options: ["Led Zeppelin I", "Led Zeppelin II", "Physical Graffiti – Led Zeppelin", "Houses of the Holy – Led Zeppelin"] },
    { q: "Hvilket album viser en mur af hvide mursten?", a: "The Wall – Pink Floyd", options: ["The Wall – Pink Floyd", "Another Brick in the Wall – Pink Floyd", "The Dark Side of the Moon – Pink Floyd", "Animals – Pink Floyd"] },
    { q: "Hvilket albums cover er helt sort med kun bandets navn i sort-på-sort?", a: "The Black Album – Metallica", options: ["The Black Album – Metallica", "Back in Black – AC/DC", "Blackout – Scorpions", "Black Sabbath – Black Sabbath"] },
    { q: "Hvilket album viser en kvinde der hæver armen med lyn og energi?", a: "Nevermind the Bollocks – Sex Pistols", options: ["Nevermind the Bollocks – Sex Pistols", "Parallel Lines – Blondie", "Horses – Patti Smith", "Nevermind – Nirvana"] },
    { q: "Hvilket album har en jæt-sort-hvid foto af en kvinde i hvid skjorte?", a: "Horses – Patti Smith", options: ["Horses – Patti Smith", "Easter – Patti Smith", "Parallel Lines – Blondie", "Pretenders – The Pretenders"] },
    { q: "Hvilket album viser en ko?", a: "Atom Heart Mother – Pink Floyd", options: ["Atom Heart Mother – Pink Floyd", "Aqualung – Jethro Tull", "Band on the Run – Wings", "Harvest – Neil Young"] },
    { q: "Hvilket album viser et fly der styrter i en bygning?", a: "Led Zeppelin – Led Zeppelin I (Hindenburg)", options: ["Led Zeppelin – Led Zeppelin I (Hindenburg)", "Fly by Night – Rush", "Mothership – Led Zeppelin", "World Record – Van der Graaf Generator"] },
    { q: "Hvilket album viser 4 symboler i stedet for titel/bandnavn?", a: "Led Zeppelin IV", options: ["Led Zeppelin IV", "Led Zeppelin III", "Houses of the Holy", "Physical Graffiti"] },
    { q: "Hvilket album har Sgt. Pepper-kostumet og en stor flok berømtheder?", a: "Sgt. Pepper's Lonely Hearts Club Band – The Beatles", options: ["Sgt. Pepper's Lonely Hearts Club Band – The Beatles", "Abbey Road – The Beatles", "Magical Mystery Tour – The Beatles", "Let It Be – The Beatles"] },
    { q: "Hvilket album viser en mand i ild på scenen?", a: "Live After Death – Iron Maiden", options: ["Live After Death – Iron Maiden", "Made in Japan – Deep Purple", "Alive! – Kiss", "Frampton Comes Alive – Peter Frampton"] },
    { q: "Hvilket album har en lyseblå/hvid farve med kun ordet WEEZER?", a: "Weezer (Blue Album)", options: ["Weezer (Blue Album)", "Weezer (Green Album)", "OK Computer – Radiohead", "Parklife – Blur"] },
    { q: "Hvilket album viser et ur der smelter (Dalí-inspireret)?", a: "The Persistence of Memory er et maleri - men hvilket rockalbum bruger et ur?", options: ["Clockwork Angels – Rush", "Time – Electric Light Orchestra", "A Clockwork Orange Soundtrack", "Time Flies – Oasis"] },
    { q: "Hvilket album har et cover med mønster af sorte og hvide kors?", a: "Closer – Joy Division", options: ["Closer – Joy Division", "Unknown Pleasures – Joy Division", "Power, Corruption & Lies – New Order", "Disintegration – The Cure"] },
    { q: "Hvilket albums cover viser sorte bølgeformer (pulsar-signal)?", a: "Unknown Pleasures – Joy Division", options: ["Unknown Pleasures – Joy Division", "Closer – Joy Division", "Music for the Masses – Depeche Mode", "Kid A – Radiohead"] },
    { q: "Hvilket album har en pige med en rød ballon?", a: "Banksy er kunstner - men hvilket albums cover viser en ballon?", options: ["Nena – 99 Luftballons", "The Wall – Pink Floyd", "Banksy's Cover Art", "Coldplay – A Rush of Blood to the Head"] },
    { q: "Hvilket album viser en strand-scene med et flyende gris?", a: "Animals – Pink Floyd", options: ["Animals – Pink Floyd", "Wish You Were Here – Pink Floyd", "Atom Heart Mother – Pink Floyd", "A Momentary Lapse of Reason – Pink Floyd"] },
    { q: "Hvilket albums cover er rent hvidt med bandnavnet præget i hvidt?", a: "The Beatles (White Album)", options: ["The Beatles (White Album)", "Weezer (White Album)", "The Blank Album – Metallica", "Imagine – John Lennon"] },
    { q: "Hvilket album viser en trekantet arkitektur i orange/rødt?", a: "Screaming for Vengeance – Judas Priest", options: ["Screaming for Vengeance – Judas Priest", "Ride the Lightning – Metallica", "Master of Puppets – Metallica", "Iron Fist – Motörhead"] },
    { q: "Hvilket album har et cover med en pool og en nøgen kvinde under vand?", a: "Nevermind – Nirvana (baby i pool)", options: ["Nevermind – Nirvana", "Ten – Pearl Jam", "Superunknown – Soundgarden", "In Utero – Nirvana"] },
    { q: "Hvilket album viser et øje og en pyramide?", a: "Eye in the Sky – The Alan Parsons Project", options: ["Eye in the Sky – The Alan Parsons Project", "The Dark Side of the Moon – Pink Floyd", "Pyramid – The Alan Parsons Project", "All Seeing Eye – Asia"] },
    { q: "Hvilket album har et cover med en mand der sidder alene ved et bord med stjerner?", a: "Breakfast in America – Supertramp", options: ["Breakfast in America – Supertramp", "Crime of the Century – Supertramp", "Brothers in Arms – Dire Straits", "Aja – Steely Dan"] },
    { q: "Hvilket album viser en guitar i blåt neon-lys?", a: "Brothers in Arms – Dire Straits", options: ["Brothers in Arms – Dire Straits", "Sultans of Swing – Dire Straits", "Money for Nothing – Dire Straits", "Love Over Gold – Dire Straits"] },
    { q: "Hvilket album har et berømt sort/hvid stribet cover med en lynlås?", a: "Sticky Fingers – The Rolling Stones (Warhol lynlås)", options: ["Sticky Fingers – The Rolling Stones", "Exile on Main St. – The Rolling Stones", "Zipper – Alice Cooper", "Loaded – The Velvet Underground"] },
    { q: "Hvilket album viser et 'OK Computer' motorvejs-landskab?", a: "OK Computer – Radiohead", options: ["OK Computer – Radiohead", "The Bends – Radiohead", "Kid A – Radiohead", "Hail to the Thief – Radiohead"] },
    { q: "Hvilket album viser King Kong på en bygning med et fly?", a: "News of the World – Queen", options: ["News of the World – Queen", "A Night at the Opera – Queen", "Sheer Heart Attack – Queen", "Jazz – Queen"] }
  ],
  "Årtier Mix": [
    { q: "Hvem havde det bedst sælgende album nogensinde med 'Thriller'?", a: "Michael Jackson", options: ["Michael Jackson", "The Beatles", "Elvis Presley", "Elton John"] },
    { q: "Hvilket instrument er Keith Richards mest kendt for at spille?", a: "Guitar", options: ["Guitar", "Bas", "Keyboard", "Trommer"] },
    { q: "Hvem skrev 'Bridge over Troubled Water'?", a: "Simon & Garfunkel", options: ["Simon & Garfunkel", "The Beatles", "Elton John", "Cat Stevens"] },
    { q: "Hvilket land kommer ABBA fra?", a: "Sverige", options: ["Sverige", "Norge", "Danmark", "Finland"] },
    { q: "Hvem er 'The King of Rock and Roll'?", a: "Elvis Presley", options: ["Elvis Presley", "Chuck Berry", "Little Richard", "Jerry Lee Lewis"] },
    { q: "Hvilket band dannede supergruppen 'Cream' med Eric Clapton?", a: "Cream (Clapton, Baker, Bruce)", options: ["Cream (Clapton, Baker, Bruce)", "Led Zeppelin", "The Yardbirds", "Blind Faith"] },
    { q: "Hvem sang 'Hallelujah' (original)?", a: "Leonard Cohen", options: ["Jeff Buckley", "Leonard Cohen", "Bob Dylan", "Rufus Wainwright"] },
    { q: "Hvilket år blev MTV lanceret?", a: "1981", options: ["1979", "1981", "1983", "1985"] },
    { q: "Hvem er den mest streamede kunstner på Spotify (per 2024)?", a: "The Weeknd (Blinding Lights)", options: ["The Weeknd (Blinding Lights)", "Drake", "Ed Sheeran", "Bad Bunny"] },
    { q: "Hvilket band opfandt begrebet 'heavy metal'?", a: "Black Sabbath", options: ["Black Sabbath", "Led Zeppelin", "Deep Purple", "Judas Priest"] },
    { q: "Hvem sang 'Respect' (mest kendte version)?", a: "Aretha Franklin", options: ["Aretha Franklin", "Otis Redding", "Tina Turner", "Diana Ross"] },
    { q: "Hvilket instrument spillede Jimi Hendrix?", a: "Guitar", options: ["Guitar", "Bas", "Trommer", "Keyboard"] },
    { q: "Hvem er kendt som 'Queen of Pop'?", a: "Madonna", options: ["Madonna", "Whitney Houston", "Beyoncé", "Janet Jackson"] },
    { q: "Hvilket band tog sit navn fra en blytung luftskib-joke?", a: "Led Zeppelin", options: ["Led Zeppelin", "Iron Maiden", "Iron Butterfly", "Black Sabbath"] },
    { q: "Hvem havde det berømte Woodstock-nummer med 'Star-Spangled Banner' på guitar?", a: "Jimi Hendrix", options: ["Jimi Hendrix", "Janis Joplin", "The Who", "Santana"] },
    { q: "Hvem er forsanger i Tøsedrengene?", a: "Michael Falch", options: ["Michael Falch", "Steffen Brandt", "Kim Larsen", "Lars H.U.G."] },
    { q: "Hvilken by er Beatles fra?", a: "Liverpool", options: ["Liverpool", "London", "Manchester", "Birmingham"] },
    { q: "Hvem producerede Michael Jacksons 'Thriller'-album?", a: "Quincy Jones", options: ["Quincy Jones", "Phil Spector", "Rick Rubin", "Dr. Dre"] },
    { q: "Hvilket band hed oprindeligt 'Smile' før de skiftede navn?", a: "Queen", options: ["Queen", "Genesis", "Pink Floyd", "The Police"] },
    { q: "Hvem sang den danske version af 'Barbie Girl'?", a: "Aqua (sang kun på engelsk)", options: ["Aqua (sang kun på engelsk)", "Bamses Venner", "Shu-bi-dua", "De Nattergale"] },
    { q: "Hvem er den mest vindende kunstner ved Grammy Awards?", a: "Beyoncé", options: ["Beyoncé", "Georg Solti", "Quincy Jones", "Stevie Wonder"] },
    { q: "Hvilket instrument spillede Elton John som sit primære?", a: "Klaver", options: ["Klaver", "Guitar", "Saxofon", "Trommer"] },
    { q: "Hvem startede Motown Records?", a: "Berry Gordy", options: ["Berry Gordy", "Phil Spector", "Quincy Jones", "Sam Cooke"] },
    { q: "Hvilket band spillede på taget af Apple Corps i London i 1969?", a: "The Beatles", options: ["The Beatles", "The Rolling Stones", "The Who", "Led Zeppelin"] },
    { q: "Hvad hedder Tommy Seebachs mest kendte sang?", a: "Krøller eller ej", options: ["Krøller eller ej", "Apache", "Under Stjernerne", "Hip Hurra"] },
    { q: "Hvem har solgt flest albums globalt?", a: "The Beatles", options: ["The Beatles", "Elvis Presley", "Michael Jackson", "Elton John"] },
    { q: "Hvilket år blev 'Smells Like Teen Spirit' udgivet?", a: "1991", options: ["1989", "1991", "1993", "1994"] },
    { q: "Hvem designede det berømte Rolling Stones-tungelogo?", a: "John Pasche", options: ["John Pasche", "Andy Warhol", "Peter Blake", "Storm Thorgerson"] },
    { q: "Hvem var den første kvinde optaget i Rock and Roll Hall of Fame?", a: "Aretha Franklin", options: ["Aretha Franklin", "Janis Joplin", "Tina Turner", "Madonna"] },
    { q: "Hvilket band havde det længste koncert-residency i Las Vegas?", a: "Elton John", options: ["Elton John", "Celine Dion", "Britney Spears", "Cher"] },
    { q: "Hvem sang 'Somebody to Love' — Queen eller Jefferson Airplane?", a: "Begge!", options: ["Begge!", "Kun Queen", "Kun Jefferson Airplane", "Ingen af dem"] }
  ]
};
